"""The persistent Data Library's domain model (build plan Phase 9A, 9B).

The Data Library is where ForgeXL keeps *business data* — sales history, sample
history and account-assignment snapshots — as opposed to the ephemeral *runtime
state* of a Run, which lives in :mod:`app.services.run_store`. The build plan
states the separation as a rule of its own:

    RunStore     -> temporary execution/runtime state
    Data Library -> persistent business datasets used across Runs

This module models what the library holds. It does not decide where any of it
is written: that belongs to :mod:`app.services.data_library`, so no business
logic ever names a filesystem location (build plan 9A).

Three kinds of value live here:

* :class:`DatasetDefinition` — a logical dataset ForgeXL knows about, declared
  in code. The three the build plan requires are declared at the bottom of this
  module.
* :class:`Dataset` and :class:`DatasetVersion` — the records the library
  persists. Pydantic, because they are written to disk as JSON and validated
  again when they are read back; a record that no longer validates is a
  corrupt record, and saying so is the point.
* :class:`DatasetCommit` — the request to commit one version. A plain frozen
  dataclass, because it carries a Polars DataFrame, which is never serialised
  and which Pydantic could not validate anyway. The same reasoning that keeps
  :class:`~app.actions.base.ActionResult` and
  :class:`~app.models.run.RunResult` out of Pydantic.

Identity rules, both of which exist so a client-supplied value can never become
a filesystem path:

* A dataset ID is a lowercase identifier declared by ForgeXL code
  (:func:`parse_dataset_id`).
* A dataset version ID is generated by ForgeXL as a UUID and validated as one
  (:func:`new_version_id`, :func:`parse_version_id`) — the same convention Run
  IDs follow, and the reason build plan 9B insists version IDs are not derived
  from user filenames.
"""

from __future__ import annotations

import hashlib
import re
import uuid
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from datetime import date, datetime, timezone
from enum import Enum

import polars as pl
from pydantic import BaseModel, ConfigDict, Field, model_validator

from app.errors import (
    InvalidDatasetCommitError,
    UnknownDatasetError,
    UnknownDatasetVersionError,
    WorkbenchError,
)
from app.models.schemas import ColumnSchema

#: Version of the persisted Data Library record format. Bump when the shape of
#: ``dataset.json`` or ``version.json`` changes incompatibly, so a record
#: written by an older build stays identifiable rather than being misread.
#:
#: Mirrors :data:`app.models.schemas.MANIFEST_SCHEMA_VERSION`, and exists for
#: the same reason: persisted state outlives the code that wrote it.
LIBRARY_SCHEMA_VERSION = 1


# ---------------------------------------------------------------------------
# Identity
# ---------------------------------------------------------------------------

#: A dataset ID is a lowercase snake_case identifier. It is declared by
#: ForgeXL code, never by a user, and it is the one value that becomes a
#: directory name — so it is checked against this before it is used as one.
DATASET_ID_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")

#: A reporting period is a calendar month, canonically ``YYYY-MM``. Months
#: sort correctly as text in this form, which is why it is the stored form.
PERIOD_PATTERN = re.compile(r"^(\d{4})-(0[1-9]|1[0-2])$")


def parse_dataset_id(raw: str) -> str:
    """Validate a dataset ID, returning it unchanged.

    Anything that is not a plain lowercase identifier — a path fragment, an
    absolute path, a name with separators or spaces — raises
    :class:`~app.errors.UnknownDatasetError` rather than reaching a filesystem.
    An unknown-but-well-formed ID is reported by the library itself; this is
    only about the shape.
    """
    if not isinstance(raw, str) or not DATASET_ID_PATTERN.fullmatch(raw):
        raise UnknownDatasetError(
            "That is not a valid dataset ID.", details={"dataset_id": raw}
        )
    return raw


def new_version_id() -> str:
    """Generate the ID of one committed dataset version (build plan 9B).

    ForgeXL generates it. It is never derived from the uploaded filename, which
    is untrusted text and is recorded as metadata only.
    """
    return str(uuid.uuid4())


def parse_version_id(raw: str) -> str:
    """Validate a dataset version ID, returning its canonical form.

    Accepts only the canonical string form of a UUID, exactly as
    :func:`app.models.run.parse_run_id` does for Run IDs. A truncated,
    traversal-shaped or invented ID is refused here rather than being used to
    build a path.
    """
    try:
        parsed = uuid.UUID(raw)
    except (ValueError, AttributeError, TypeError):
        raise UnknownDatasetVersionError(
            "That is not a valid dataset version ID.", details={"version_id": raw}
        ) from None
    if str(parsed) != raw.lower():
        raise UnknownDatasetVersionError(
            "That is not a valid dataset version ID.", details={"version_id": raw}
        )
    return str(parsed)


def parse_period(raw: str) -> str:
    """Validate a reporting period, returning its canonical ``YYYY-MM`` form.

    A period is a calendar month. It is validated rather than accepted as free
    text because it is an identity in this system: "the September 2026 sales
    version" and "the September 2026 ownership snapshot" have to name the same
    month in the same way for a report to be reproducible (build plan 9E).

    Raises:
        InvalidDatasetCommitError: the value is not a ``YYYY-MM`` month.
    """
    if not isinstance(raw, str) or not PERIOD_PATTERN.fullmatch(raw):
        raise InvalidDatasetCommitError(
            "A reporting period must be a calendar month written as YYYY-MM, "
            f"for example 2026-09. Received {raw!r}.",
            details={"period": raw},
        )
    return raw


def content_hash(payload: bytes) -> str:
    """Return the SHA-256 hex digest of an uploaded source file.

    Defined in one place so every caller hashes the same way. Build plan 10C
    detects an already-imported identical file by comparing this digest, which
    only works if there is exactly one definition of it.
    """
    return hashlib.sha256(payload).hexdigest()


def now() -> datetime:
    """The timestamp a Data Library record carries, always UTC."""
    return datetime.now(timezone.utc)


@contextmanager
def _as_validation_failure() -> Iterator[None]:
    """Re-raise an identity refusal as the ``ValueError`` Pydantic understands.

    The :func:`parse_dataset_id` / :func:`parse_version_id` / :func:`parse_period`
    rules are defined once and used in two places: at the boundary, where a bad
    ID is a 404 or a 422 with a code the UI can act on, and inside the model
    validators below, where a bad ID means *this stored record is not valid*.

    Pydantic converts only ``ValueError`` and ``AssertionError`` into a
    :class:`~pydantic.ValidationError`; anything else escapes as itself. That
    difference matters: a corrupt ``version.json`` must surface as an invalid
    record — which the Data Library reports as corrupt persistent state — and
    not as ``UnknownDatasetVersionError``, which means the perfectly healthy
    "no such version". This adapter keeps one definition of each rule while
    letting each context report the failure it actually has.
    """
    try:
        yield
    except WorkbenchError as error:
        raise ValueError(error.message) from error


# ---------------------------------------------------------------------------
# Dataset definitions
# ---------------------------------------------------------------------------


class DatasetKind(str, Enum):
    """What a dataset's versions mean together (build plan 9B "dataset type").

    The distinction is semantic rather than structural — both kinds are stored
    the same way — and it is the distinction build plan 9E turns on:

    * :attr:`HISTORY` accumulates. Each version adds a reporting period, and a
      report reads many of them together. Sales and sample history are this.
    * :attr:`SNAPSHOT` does not accumulate. Each version states the whole truth
      as of one reporting period, and a report reads exactly the period it is
      reporting on. Account assignments are this: an account owned by one rep
      in September and another in November must regenerate September's report
      against September's ownership, not today's.
    """

    HISTORY = "history"
    SNAPSHOT = "snapshot"


class DatasetDefinition(BaseModel):
    """A logical dataset ForgeXL knows about, declared in code.

    Declared rather than discovered, for the same reason Actions are: the
    library is application code, not a plugin loader. The definitions the build
    plan requires are :data:`KNOWN_DATASETS` at the bottom of this module.
    """

    model_config = ConfigDict(frozen=True)

    id: str = Field(description="Stable logical dataset ID, e.g. 'sales_history'.")
    kind: DatasetKind
    label: str = Field(description="Human-readable dataset name.")
    description: str

    @model_validator(mode="after")
    def _check_id(self) -> DatasetDefinition:
        with _as_validation_failure():
            parse_dataset_id(self.id)
        return self


class Dataset(BaseModel):
    """A dataset as the library has recorded it (``dataset.json``).

    Created from a :class:`DatasetDefinition` the first time the dataset is
    used. It carries `created_at` because a definition is code and this is a
    record: when the dataset first existed in *this* library is a fact only the
    library knows.
    """

    model_config = ConfigDict(frozen=True)

    schema_version: int = LIBRARY_SCHEMA_VERSION
    id: str
    kind: DatasetKind
    label: str
    description: str
    created_at: datetime

    @classmethod
    def of(
        cls, definition: DatasetDefinition, *, created_at: datetime | None = None
    ) -> Dataset:
        """Build the record for `definition`, stamped now unless told otherwise."""
        return cls(
            id=definition.id,
            kind=definition.kind,
            label=definition.label,
            description=definition.description,
            created_at=created_at or now(),
        )

    def definition(self) -> DatasetDefinition:
        """Return the declaration this record was created from."""
        return DatasetDefinition(
            id=self.id,
            kind=self.kind,
            label=self.label,
            description=self.description,
        )


# ---------------------------------------------------------------------------
# Dataset versions
# ---------------------------------------------------------------------------


class DatasetVersion(BaseModel):
    """One immutable committed version of one dataset (``version.json``).

    Build plan 9B lists what a version must record. Each item, and where it is:

    ==============================  =====================================
    build plan 9B                   field
    ==============================  =====================================
    dataset ID                      ``dataset_id``
    version ID                      ``version_id``
    dataset type                    ``dataset_kind``
    reporting/effective period      ``period``
    created timestamp               ``created_at``
    source filename                 ``source_filename``
    source byte size                ``source_byte_size``
    source content hash             ``source_sha256``
    row count                       ``row_count``
    column count                    ``column_count``
    column schema                   ``column_schema``
    parser information              ``parser_engine``, ``worksheet``
    minimum / maximum date          ``min_date``, ``max_date``
    report month                    ``period`` — see below
    replacement / supersession      ``supersedes``, ``supersession_reason``
    ==============================  =====================================

    **Report month and reporting period are one field on purpose.** For a
    monthly history version the reporting period *is* the report month; for a
    snapshot it is the month the snapshot is effective for. Recording the same
    month twice under two names would create two things that can disagree, and
    a version whose two months disagreed would be unreproducible in exactly the
    way build plan 9E exists to prevent.

    `dataset_kind` is denormalised onto the version deliberately, the same way
    :class:`~app.models.schemas.ActionReference` is copied into a Run manifest:
    a committed version is an audit record and has to stand on its own.

    **Immutability (build plan 9D).** Nothing rewrites a version once it is
    committed. A period is corrected by committing a *new* version that names
    the old one in `supersedes`, with `supersession_reason` explaining why. The
    reverse direction — "which version replaced this one" — is derived by the
    library from those forward pointers rather than written back into a record
    that is supposed to never change.
    """

    model_config = ConfigDict(frozen=True)

    schema_version: int = LIBRARY_SCHEMA_VERSION

    dataset_id: str
    version_id: str
    dataset_kind: DatasetKind

    period: str | None = Field(
        default=None,
        description=(
            "Reporting/effective period as YYYY-MM. Null only for a version "
            "that is not scoped to one month, such as a historical bootstrap "
            "covering several (build plan 10G)."
        ),
    )

    created_at: datetime

    source_filename: str = Field(
        description=(
            "The filename of the file this version was built from. Metadata "
            "only: it never becomes a path (build plan section 16)."
        )
    )
    source_byte_size: int
    source_sha256: str = Field(
        description="SHA-256 of the source file's bytes, as hex."
    )
    parser_engine: str | None = Field(
        default=None,
        description="Engine that read the source, recorded so a fallback is never silent.",
    )
    worksheet: str | None = Field(
        default=None, description="Worksheet read from an XLSX source; null for CSV."
    )

    row_count: int
    column_count: int
    column_schema: tuple[ColumnSchema, ...]

    min_date: date | None = Field(
        default=None, description="Earliest date found in the data, where it has one."
    )
    max_date: date | None = Field(
        default=None, description="Latest date found in the data, where it has one."
    )

    supersedes: str | None = Field(
        default=None,
        description="Version ID this version replaces (build plan 9D).",
    )
    supersession_reason: str | None = Field(
        default=None,
        description="Why the replaced version was replaced. Required alongside `supersedes`.",
    )

    @model_validator(mode="after")
    def _check_identity_and_supersession(self) -> DatasetVersion:
        with _as_validation_failure():
            parse_dataset_id(self.dataset_id)
            parse_version_id(self.version_id)
            if self.period is not None:
                parse_period(self.period)
            if self.supersedes is not None:
                parse_version_id(self.supersedes)

        if self.supersedes is not None:
            if self.supersedes == self.version_id:
                raise ValueError("A dataset version cannot supersede itself.")
            if not (self.supersession_reason or "").strip():
                raise ValueError(
                    "A version that supersedes another must record why "
                    "(build plan 9D)."
                )
        elif self.supersession_reason is not None:
            raise ValueError(
                "supersession_reason is only meaningful alongside supersedes."
            )

        if self.column_count != len(self.column_schema):
            raise ValueError(
                "column_count must match the number of columns described."
            )
        return self

    @property
    def columns(self) -> tuple[str, ...]:
        """This version's column names, in column order."""
        return tuple(column.name for column in self.column_schema)


@dataclass(frozen=True)
class DatasetCommit:
    """The request to commit one new version of a dataset (build plan 9B).

    A plain dataclass rather than a Pydantic model because it carries the
    DataFrame itself. What gets *persisted* is the validated
    :class:`DatasetVersion` the library derives from this.

    Provenance is required, not optional. A version whose source is unknown
    cannot be audited, cannot be recognised as an accidental re-upload
    (build plan 10C) and cannot explain a report it fed. :meth:`from_upload`
    derives the size and the hash from the bytes so a caller never has to.
    """

    #: The parsed source, exactly as it will be stored. This is the full
    #: snapshot: the library keeps no second copy of the raw upload.
    frame: pl.DataFrame

    #: The filename the file arrived under. Metadata only.
    source_filename: str
    source_byte_size: int
    source_sha256: str

    period: str | None = None
    parser_engine: str | None = None
    worksheet: str | None = None
    min_date: date | None = None
    max_date: date | None = None

    #: The version this one replaces, and why (build plan 9D). Both or neither.
    supersedes: str | None = None
    supersession_reason: str | None = None

    @classmethod
    def from_upload(
        cls,
        frame: pl.DataFrame,
        *,
        filename: str,
        payload: bytes,
        **fields: object,
    ) -> DatasetCommit:
        """Build a commit from the uploaded bytes the frame was parsed from.

        The byte size and content hash are measured here rather than passed in,
        so the two facts that identify a source file always agree with the file
        itself.
        """
        return cls(
            frame=frame,
            source_filename=filename,
            source_byte_size=len(payload),
            source_sha256=content_hash(payload),
            **fields,  # type: ignore[arg-type]
        )


# ---------------------------------------------------------------------------
# The datasets ForgeXL knows about (build plan Phase 9, "first required
# persistent datasets")
# ---------------------------------------------------------------------------

SALES_HISTORY = DatasetDefinition(
    id="sales_history",
    kind=DatasetKind.HISTORY,
    label="Sales History",
    description=(
        "Monthly sales data, one committed version per reporting period. "
        "Versions accumulate: a report reads every month it covers."
    ),
)

SAMPLE_HISTORY = DatasetDefinition(
    id="sample_history",
    kind=DatasetKind.HISTORY,
    label="Sample History",
    description=(
        "Monthly sample data, kept as a dataset of its own. Samples are not "
        "sales and are never folded into sales history, however similar the "
        "two source files look."
    ),
)

ACCOUNT_ASSIGNMENTS = DatasetDefinition(
    id="account_assignments",
    kind=DatasetKind.SNAPSHOT,
    label="Account Assignments",
    description=(
        "Sales-rep/account ownership as of one reporting period. Stored as a "
        "snapshot per month, so regenerating an older report uses the "
        "ownership that applied then rather than the ownership that applies "
        "now."
    ),
)

#: Every dataset ForgeXL currently persists, in a stable order.
KNOWN_DATASETS: tuple[DatasetDefinition, ...] = (
    SALES_HISTORY,
    SAMPLE_HISTORY,
    ACCOUNT_ASSIGNMENTS,
)


def known_dataset(dataset_id: str) -> DatasetDefinition | None:
    """Return the declared definition for `dataset_id`, or None.

    Unknown IDs never fall back to a near match, exactly as the Action registry
    refuses to guess (build plan Phase 2.4).
    """
    for definition in KNOWN_DATASETS:
        if definition.id == dataset_id:
            return definition
    return None