"""Export service tests (build plan 3.10 and 6D.7).

Proves the generated bytes are genuinely readable files, not merely bytes with
the right name — and that generating them writes nothing to the filesystem.

Until Phase 6D these tests read three artifacts back off disk. The exports are
built in memory now, so each assertion is made against the bytes the service
returned instead of against a file it wrote.
"""

from __future__ import annotations

import io
import zipfile
from pathlib import Path

import polars as pl
import pytest

from app.services import export, parser

FRAME = pl.DataFrame(
    {
        "SKU": ["A1", "A2", "A3"],
        "Producer": ["Château Margaux", "Bodegas Muñoz", None],
        "Volume": [750, 1500, 375],
    }
)


# ---------------------------------------------------------------------------
# CSV (build plan 6D.7; 6F.1 formalises the download contract)
# ---------------------------------------------------------------------------


def test_the_csv_export_round_trips() -> None:
    payload = export.to_csv_bytes(FRAME)

    reloaded = pl.read_csv(io.BytesIO(payload))

    assert reloaded.columns == FRAME.columns
    assert reloaded.height == 3
    assert reloaded["Producer"].to_list() == [
        "Château Margaux",
        "Bodegas Muñoz",
        None,
    ]


def test_the_csv_header_is_the_frame_column_order() -> None:
    payload = export.to_csv_bytes(FRAME)

    assert payload.decode("utf-8").splitlines()[0] == "SKU,Producer,Volume"


def test_an_empty_result_still_produces_a_header_row() -> None:
    payload = export.to_csv_bytes(FRAME.head(0))

    assert payload.decode("utf-8").strip() == "SKU,Producer,Volume"


# ---------------------------------------------------------------------------
# XLSX
# ---------------------------------------------------------------------------


def test_the_xlsx_export_is_a_real_workbook_that_round_trips() -> None:
    payload = export.to_xlsx_bytes(FRAME, worksheet="product_master")

    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        assert "xl/workbook.xml" in archive.namelist()

    # Read back through the application's own reader: an export this
    # application could not itself ingest fails here.
    reloaded = parser.parse_tabular_bytes(payload, ".xlsx").frame
    assert reloaded.columns == FRAME.columns
    assert reloaded.height == 3
    assert reloaded["SKU"].to_list() == ["A1", "A2", "A3"]
    assert reloaded["Volume"].to_list() == [750, 1500, 375]


def test_accented_values_survive_the_excel_round_trip() -> None:
    payload = export.to_xlsx_bytes(FRAME, worksheet="product_master")

    reloaded = parser.parse_tabular_bytes(payload, ".xlsx").frame

    assert reloaded["Producer"].to_list()[:2] == ["Château Margaux", "Bodegas Muñoz"]


def test_the_worksheet_is_named_after_the_output() -> None:
    payload = export.to_xlsx_bytes(FRAME, worksheet="product_master")

    assert parser.parse_tabular_bytes(payload, ".xlsx").worksheet == "product_master"


@pytest.mark.parametrize(
    ("output_id", "expected"),
    [
        ("result", "result"),
        ("product_master", "product_master"),
        ("a" * 40, "a" * 31),
    ],
)
def test_a_worksheet_name_never_exceeds_excels_limit(
    output_id: str, expected: str
) -> None:
    assert export.worksheet_name(output_id) == expected
    assert len(export.worksheet_name(output_id)) <= 31


def test_an_empty_result_still_produces_a_valid_workbook() -> None:
    payload = export.to_xlsx_bytes(FRAME.head(0), worksheet="result")

    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        assert "xl/workbook.xml" in archive.namelist()


# ---------------------------------------------------------------------------
# Format dispatch
# ---------------------------------------------------------------------------


def test_to_bytes_dispatches_on_the_requested_format() -> None:
    csv_payload = export.to_bytes(FRAME, export.CSV_FORMAT, name="result")
    xlsx_payload = export.to_bytes(FRAME, export.XLSX_FORMAT, name="result")

    assert csv_payload == export.to_csv_bytes(FRAME)
    assert xlsx_payload.startswith(b"PK")


def test_an_unknown_format_is_refused() -> None:
    with pytest.raises(ValueError):
        export.to_bytes(FRAME, "parquet", name="result")


def test_the_offered_formats_are_csv_then_xlsx() -> None:
    assert export.EXPORT_FORMATS == ("csv", "xlsx")


# ---------------------------------------------------------------------------
# 6D.7 Nothing is written
# ---------------------------------------------------------------------------


def test_generating_an_export_writes_nothing(
    tmp_path: Path, runs_dir: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Build plan 6D: a Run needs no ``working/`` or ``exports/`` directory."""
    empty = tmp_path / "cwd"
    empty.mkdir()
    monkeypatch.chdir(empty)

    export.to_csv_bytes(FRAME)
    export.to_xlsx_bytes(FRAME, worksheet="result")

    assert list(empty.iterdir()) == []
    assert list(runs_dir.rglob("*")) == []


def test_the_service_no_longer_writes_artifacts() -> None:
    """The path-writing API is gone, not merely unused."""
    assert not hasattr(export, "write_output")
    assert not hasattr(export, "write_parquet")
    assert not hasattr(export, "write_csv")
    assert not hasattr(export, "write_xlsx")