"""The Data Library's domain model (build plan 9B).

These tests are about the *records*, independent of where they are stored:
what a dataset version must record, what a version ID may be, what a reporting
period may be, and the rules a supersession has to satisfy before anything is
written.

The storage half is in `test_data_library.py`; the durability half is in
`test_library_persistence.py`.
"""

from __future__ import annotations

import json
from datetime import date, datetime, timezone

import polars as pl
import pytest
from pydantic import ValidationError

from app.errors import (
    InvalidDatasetCommitError,
    UnknownDatasetError,
    UnknownDatasetVersionError,
)
from app.models.library import (
    ACCOUNT_ASSIGNMENTS,
    KNOWN_DATASETS,
    LIBRARY_SCHEMA_VERSION,
    SALES_HISTORY,
    SAMPLE_HISTORY,
    Dataset,
    DatasetCommit,
    DatasetDefinition,
    DatasetKind,
    DatasetVersion,
    content_hash,
    known_dataset,
    new_version_id,
    parse_dataset_id,
    parse_period,
    parse_version_id,
)
from app.models.schemas import ColumnKind, ColumnSchema


def _version(**overrides) -> DatasetVersion:
    """A complete, valid version record; override one field per test."""
    fields = {
        "dataset_id": "sales_history",
        "version_id": new_version_id(),
        "dataset_kind": DatasetKind.HISTORY,
        "period": "2026-09",
        "created_at": datetime(2026, 9, 30, 12, 0, tzinfo=timezone.utc),
        "source_filename": "September Sales.csv",
        "source_byte_size": 4096,
        "source_sha256": content_hash(b"September Sales"),
        "parser_engine": "polars-csv",
        "row_count": 3,
        "column_count": 2,
        "column_schema": (
            ColumnSchema(name="Account", dtype="String", kind=ColumnKind.TEXT),
            ColumnSchema(name="Amount", dtype="Float64", kind=ColumnKind.NUMBER),
        ),
    }
    fields.update(overrides)
    return DatasetVersion(**fields)


# ---------------------------------------------------------------------------
# 9A — the datasets ForgeXL declares
# ---------------------------------------------------------------------------


def test_the_three_required_datasets_are_declared() -> None:
    """Build plan Phase 9: "The first required persistent datasets are ..."."""
    assert [definition.id for definition in KNOWN_DATASETS] == [
        "sales_history",
        "sample_history",
        "account_assignments",
    ]


def test_account_assignments_is_a_snapshot_and_the_histories_are_not() -> None:
    """Build plan 9E: ownership is stored per effective period, not as one file."""
    assert ACCOUNT_ASSIGNMENTS.kind is DatasetKind.SNAPSHOT
    assert SALES_HISTORY.kind is DatasetKind.HISTORY
    assert SAMPLE_HISTORY.kind is DatasetKind.HISTORY


def test_sales_and_samples_are_separate_logical_datasets() -> None:
    """Build plan 10D forbids folding one into the other; they start apart."""
    assert SALES_HISTORY.id != SAMPLE_HISTORY.id


def test_a_declared_dataset_is_found_by_its_stable_id() -> None:
    assert known_dataset("sales_history") is SALES_HISTORY


def test_an_undeclared_dataset_id_resolves_to_nothing() -> None:
    """No near matches, exactly as the Action registry refuses to guess."""
    assert known_dataset("sales") is None
    assert known_dataset("sales_histories") is None


def test_a_definition_with_an_unusable_id_is_refused() -> None:
    with pytest.raises(ValidationError):
        DatasetDefinition(
            id="../escape",
            kind=DatasetKind.HISTORY,
            label="Escape",
            description="Never valid.",
        )


# ---------------------------------------------------------------------------
# 9B — identity
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "dataset_id", ["sales_history", "s", "a1", "account_assignments"]
)
def test_a_well_formed_dataset_id_is_accepted(dataset_id: str) -> None:
    assert parse_dataset_id(dataset_id) == dataset_id


@pytest.mark.parametrize(
    "dataset_id",
    [
        "../sales_history",
        "sales history",
        "sales-history",
        "/etc/passwd",
        "Sales_History",
        "1sales",
        "",
        "sales_history/versions",
        "..",
        ".",
    ],
)
def test_an_unsafe_dataset_id_is_refused_for_its_shape(dataset_id: str) -> None:
    """Refused before the library is asked whether it holds one.

    A dataset ID is the one value that becomes a directory name, so its shape
    is checked rather than trusted.
    """
    with pytest.raises(UnknownDatasetError):
        parse_dataset_id(dataset_id)


def test_a_generated_version_id_is_a_uuid() -> None:
    """Build plan 9B: generated by ForgeXL, never from a user filename."""
    generated = new_version_id()

    assert parse_version_id(generated) == generated


def test_two_generated_version_ids_differ() -> None:
    assert new_version_id() != new_version_id()


@pytest.mark.parametrize(
    "version_id",
    [
        "../../etc/passwd",
        "September Sales.csv",
        "not-a-uuid",
        "",
        "6e444a2b371b47d5b9d589b0fbd249c9",  # no hyphens is not the canonical form
    ],
)
def test_a_version_id_that_is_not_a_uuid_is_refused(version_id: str) -> None:
    with pytest.raises(UnknownDatasetVersionError):
        parse_version_id(version_id)


def test_a_version_id_is_canonicalised_to_lowercase() -> None:
    """The same rule Run IDs follow, so a version is found however it is typed.

    Canonicalising rather than refusing is safe here because the canonical form
    is what becomes the directory name, and it is a UUID either way.
    """
    canonical = "6e444a2b-371b-47d5-b9d5-89b0fbd249c9"

    assert parse_version_id(canonical.upper()) == canonical


def test_the_content_hash_is_sha256_of_the_source_bytes() -> None:
    """One definition, so build plan 10C can compare two imports meaningfully."""
    import hashlib

    payload = b"SKU,Volume\nA-1,750ml\n"

    assert content_hash(payload) == hashlib.sha256(payload).hexdigest()


def test_identical_sources_hash_alike_and_different_ones_do_not() -> None:
    assert content_hash(b"same") == content_hash(b"same")
    assert content_hash(b"same") != content_hash(b"same ")


# ---------------------------------------------------------------------------
# 9B — reporting periods
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("period", ["2026-09", "2026-01", "2026-12", "1999-07"])
def test_a_calendar_month_is_a_valid_period(period: str) -> None:
    assert parse_period(period) == period


@pytest.mark.parametrize(
    "period",
    [
        "2026-13",
        "2026-00",
        "2026-9",
        "September 2026",
        "2026",
        "2026-09-01",
        "26-09",
        "",
        "../2026-09",
    ],
)
def test_anything_that_is_not_a_calendar_month_is_refused(period: str) -> None:
    with pytest.raises(InvalidDatasetCommitError):
        parse_period(period)


def test_periods_sort_chronologically_as_text() -> None:
    """Why YYYY-MM is the stored form: ordering needs no parsing."""
    months = ["2026-10", "2025-12", "2026-01", "2026-09"]

    assert sorted(months) == ["2025-12", "2026-01", "2026-09", "2026-10"]


# ---------------------------------------------------------------------------
# 9B — the version record
# ---------------------------------------------------------------------------


def test_a_version_records_everything_build_plan_9b_lists() -> None:
    """Each item on 9B's list, present and populated."""
    version = _version(
        min_date=date(2026, 9, 1),
        max_date=date(2026, 9, 30),
        worksheet="Sheet1",
    )

    assert version.dataset_id == "sales_history"
    assert parse_version_id(version.version_id) == version.version_id
    assert version.dataset_kind is DatasetKind.HISTORY
    assert version.period == "2026-09"
    assert version.created_at.tzinfo is not None
    assert version.source_filename == "September Sales.csv"
    assert version.source_byte_size == 4096
    assert version.source_sha256 == content_hash(b"September Sales")
    assert version.row_count == 3
    assert version.column_count == 2
    assert version.columns == ("Account", "Amount")
    assert version.parser_engine == "polars-csv"
    assert version.worksheet == "Sheet1"
    assert version.min_date == date(2026, 9, 1)
    assert version.max_date == date(2026, 9, 30)
    assert version.supersedes is None


def test_a_version_record_is_frozen() -> None:
    """A committed version is immutable in memory as well as on disk (9D)."""
    version = _version()

    with pytest.raises(ValidationError):
        version.period = "2026-10"  # type: ignore[misc]


def test_a_version_may_cover_no_single_period() -> None:
    """Build plan 10G's historical bootstrap spans several months."""
    version = _version(period=None)

    assert version.period is None


def test_a_version_column_count_must_match_its_schema() -> None:
    """The two describe the same table; a record where they disagree is wrong."""
    with pytest.raises(ValidationError):
        _version(column_count=5)


def test_a_version_id_that_is_not_a_uuid_cannot_be_recorded() -> None:
    with pytest.raises(ValidationError):
        _version(version_id="september")


def test_a_version_period_that_is_not_a_month_cannot_be_recorded() -> None:
    with pytest.raises(ValidationError):
        _version(period="September")


# ---------------------------------------------------------------------------
# 9D — supersession metadata
# ---------------------------------------------------------------------------


def test_a_replacement_records_what_it_replaces_and_why() -> None:
    replaced = new_version_id()

    version = _version(
        supersedes=replaced,
        supersession_reason="The September export was taken before month end.",
    )

    assert version.supersedes == replaced
    assert "month end" in (version.supersession_reason or "")


def test_a_replacement_without_a_reason_is_refused() -> None:
    """Build plan 9D: retain enough metadata to explain the change."""
    with pytest.raises(ValidationError):
        _version(supersedes=new_version_id())


def test_a_blank_reason_does_not_count_as_a_reason() -> None:
    with pytest.raises(ValidationError):
        _version(supersedes=new_version_id(), supersession_reason="   ")


def test_a_reason_without_a_replacement_is_refused() -> None:
    """It would explain a change the record does not claim to have made."""
    with pytest.raises(ValidationError):
        _version(supersession_reason="Corrected.")


def test_a_version_cannot_supersede_itself() -> None:
    version_id = new_version_id()

    with pytest.raises(ValidationError):
        _version(
            version_id=version_id,
            supersedes=version_id,
            supersession_reason="Nonsense.",
        )


# ---------------------------------------------------------------------------
# 9B/9C — records survive being written and read back
# ---------------------------------------------------------------------------


def test_a_version_record_round_trips_through_json() -> None:
    """The exact operation the library performs against the filesystem."""
    version = _version(
        min_date=date(2026, 9, 1),
        max_date=date(2026, 9, 30),
        supersedes=new_version_id(),
        supersession_reason="Restated.",
    )

    restored = DatasetVersion.model_validate_json(version.model_dump_json())

    assert restored == version


def test_a_dataset_record_round_trips_through_json() -> None:
    dataset = Dataset.of(SALES_HISTORY)

    restored = Dataset.model_validate_json(dataset.model_dump_json())

    assert restored == dataset
    assert restored.definition() == SALES_HISTORY


def test_a_record_carries_its_format_version() -> None:
    """So a record written by an older build stays identifiable."""
    payload = json.loads(_version().model_dump_json())

    assert payload["schema_version"] == LIBRARY_SCHEMA_VERSION


def test_a_stored_record_contains_no_filesystem_path() -> None:
    """Build plan 9C: physical locations are not part of the record."""
    payload = _version().model_dump_json()

    for fragment in ("/home/", "/Users/", "/tmp", "data/library", ".parquet"):
        assert fragment not in payload


# ---------------------------------------------------------------------------
# 9B — the commit request
# ---------------------------------------------------------------------------


def test_a_commit_measures_its_source_from_the_uploaded_bytes() -> None:
    """So the two facts that identify a source file always agree with it."""
    payload = b"Account,Amount\nAcme,10\n"
    frame = pl.DataFrame({"Account": ["Acme"], "Amount": [10]})

    commit = DatasetCommit.from_upload(
        frame, filename="September Sales.csv", payload=payload, period="2026-09"
    )

    assert commit.source_filename == "September Sales.csv"
    assert commit.source_byte_size == len(payload)
    assert commit.source_sha256 == content_hash(payload)
    assert commit.period == "2026-09"


def test_a_commit_defaults_to_no_period_and_no_supersession() -> None:
    commit = DatasetCommit(
        frame=pl.DataFrame({"Account": ["Acme"]}),
        source_filename="bootstrap.csv",
        source_byte_size=1,
        source_sha256=content_hash(b"x"),
    )

    assert commit.period is None
    assert commit.supersedes is None
    assert commit.supersession_reason is None