"""Export service tests (build plan 3.10, 6D.7 and 6F).

Proves the generated bytes are genuinely readable files, not merely bytes with
the right name — and that generating them writes nothing to the filesystem.

Until Phase 6D these tests read three artifacts back off disk. The exports are
built in memory now, so each assertion is made against the bytes the service
returned instead of against a file it wrote.

Phase 6F adds the rest of the export contract: the workbook is assembled with
no temporary file at all, an Action's several tables become several worksheets,
worksheet names are valid and unique, and downloads are named by the ForgeXL
convention.
"""

from __future__ import annotations

import html
import io
import re
import tempfile
import zipfile
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

import fastexcel
import polars as pl
import pytest

from app.services import export, parser

FRAME = pl.DataFrame(
    {
        "SKU": ["A1", "A2", "A3"],
        "Producer": ["Château Margaux", "Bodegas Muñoz", None],
        "Volume": [750, 1500, 375],
    }
)


# ---------------------------------------------------------------------------
# CSV (build plan 6D.7; 6F.1 formalises the download contract)
# ---------------------------------------------------------------------------


def test_the_csv_export_round_trips() -> None:
    payload = export.to_csv_bytes(FRAME)

    reloaded = pl.read_csv(io.BytesIO(payload))

    assert reloaded.columns == FRAME.columns
    assert reloaded.height == 3
    assert reloaded["Producer"].to_list() == [
        "Château Margaux",
        "Bodegas Muñoz",
        None,
    ]


def test_the_csv_header_is_the_frame_column_order() -> None:
    payload = export.to_csv_bytes(FRAME)

    assert payload.decode("utf-8").splitlines()[0] == "SKU,Producer,Volume"


def test_an_empty_result_still_produces_a_header_row() -> None:
    payload = export.to_csv_bytes(FRAME.head(0))

    assert payload.decode("utf-8").strip() == "SKU,Producer,Volume"


# ---------------------------------------------------------------------------
# XLSX
# ---------------------------------------------------------------------------


def test_the_xlsx_export_is_a_real_workbook_that_round_trips() -> None:
    payload = export.to_xlsx_bytes(FRAME, worksheet="product_master")

    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        assert "xl/workbook.xml" in archive.namelist()

    # Read back through the application's own reader: an export this
    # application could not itself ingest fails here.
    reloaded = parser.parse_tabular_bytes(payload, ".xlsx").frame
    assert reloaded.columns == FRAME.columns
    assert reloaded.height == 3
    assert reloaded["SKU"].to_list() == ["A1", "A2", "A3"]
    assert reloaded["Volume"].to_list() == [750, 1500, 375]


def test_accented_values_survive_the_excel_round_trip() -> None:
    payload = export.to_xlsx_bytes(FRAME, worksheet="product_master")

    reloaded = parser.parse_tabular_bytes(payload, ".xlsx").frame

    assert reloaded["Producer"].to_list()[:2] == ["Château Margaux", "Bodegas Muñoz"]


def test_the_worksheet_is_named_after_the_output() -> None:
    payload = export.to_xlsx_bytes(FRAME, worksheet="product_master")

    assert parser.parse_tabular_bytes(payload, ".xlsx").worksheet == "product_master"


@pytest.mark.parametrize(
    ("output_id", "expected"),
    [
        ("result", "result"),
        ("product_master", "product_master"),
        ("a" * 40, "a" * 31),
    ],
)
def test_a_worksheet_name_never_exceeds_excels_limit(
    output_id: str, expected: str
) -> None:
    assert export.worksheet_name(output_id) == expected
    assert len(export.worksheet_name(output_id)) <= 31


def test_an_empty_result_still_produces_a_valid_workbook() -> None:
    payload = export.to_xlsx_bytes(FRAME.head(0), worksheet="result")

    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        assert "xl/workbook.xml" in archive.namelist()


# ---------------------------------------------------------------------------
# Format dispatch
# ---------------------------------------------------------------------------


def test_to_bytes_dispatches_on_the_requested_format() -> None:
    csv_payload = export.to_bytes(FRAME, export.CSV_FORMAT, name="result")
    xlsx_payload = export.to_bytes(FRAME, export.XLSX_FORMAT, name="result")

    assert csv_payload == export.to_csv_bytes(FRAME)
    assert xlsx_payload.startswith(b"PK")


def test_an_unknown_format_is_refused() -> None:
    with pytest.raises(ValueError):
        export.to_bytes(FRAME, "parquet", name="result")


def test_the_offered_formats_are_csv_then_xlsx() -> None:
    assert export.EXPORT_FORMATS == ("csv", "xlsx")


# ---------------------------------------------------------------------------
# 6D.7 Nothing is written
# ---------------------------------------------------------------------------


def test_generating_an_export_writes_nothing(
    tmp_path: Path, runs_dir: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Build plan 6D: a Run needs no ``working/`` or ``exports/`` directory."""
    empty = tmp_path / "cwd"
    empty.mkdir()
    monkeypatch.chdir(empty)

    export.to_csv_bytes(FRAME)
    export.to_xlsx_bytes(FRAME, worksheet="result")

    assert list(empty.iterdir()) == []
    assert list(runs_dir.rglob("*")) == []


def test_the_service_no_longer_writes_artifacts() -> None:
    """The path-writing API is gone, not merely unused."""
    assert not hasattr(export, "write_output")
    assert not hasattr(export, "write_parquet")
    assert not hasattr(export, "write_csv")
    assert not hasattr(export, "write_xlsx")


# ---------------------------------------------------------------------------
# 6F.2 The workbook is built in memory — not spooled through /tmp
# ---------------------------------------------------------------------------


def test_the_workbook_is_opened_in_memory() -> None:
    """xlsxwriter must be told not to use the OS temporary directory.

    Its default is to spool the workbook's parts through ``tempfile``. Build
    plan 6F.2 asks for an in-memory binary buffer, so the option is asserted
    directly as well as observed below.
    """
    assert export.WORKBOOK_OPTIONS["in_memory"] is True


def test_generating_a_workbook_creates_no_temporary_file(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Build plan 6F.2: nothing reaches a disk, including ``/tmp``."""
    created: list[str] = []
    real_mkstemp = tempfile.mkstemp
    real_named = tempfile.NamedTemporaryFile

    def spy_mkstemp(*args, **kwargs):
        handle, path = real_mkstemp(*args, **kwargs)
        created.append(path)
        return handle, path

    def spy_named(*args, **kwargs):
        opened = real_named(*args, **kwargs)
        created.append(getattr(opened, "name", "?"))
        return opened

    monkeypatch.setattr(tempfile, "mkstemp", spy_mkstemp)
    monkeypatch.setattr(tempfile, "NamedTemporaryFile", spy_named)

    export.to_xlsx_bytes(FRAME, worksheet="Result")
    export.to_workbook_bytes([("Kept", FRAME), ("Rejected", FRAME.head(1))])

    assert created == []


def test_a_cell_beginning_with_an_equals_sign_stays_text() -> None:
    """Build plan section 16: an uploaded value is never written as a formula."""
    frame = pl.DataFrame({"Note": ["=SUM(A1:A9)", "plain"]})

    payload = export.to_xlsx_bytes(frame, worksheet="Result")

    assert export.WORKBOOK_OPTIONS["strings_to_formulas"] is False
    assert parser.parse_tabular_bytes(payload, ".xlsx").frame[
        "Note"
    ].to_list() == ["=SUM(A1:A9)", "plain"]


# ---------------------------------------------------------------------------
# 6F.3 Sensible cell values
# ---------------------------------------------------------------------------


def test_numeric_columns_carry_no_display_format() -> None:
    """A small value must not be shown as 0.000, nor a large one regrouped.

    Polars applies ``#,##0.000`` to every numeric column by default. The stored
    value stays exact either way, but what Excel *shows* is what a reader
    trusts, so numbers are presented exactly as the data holds them
    (build plan 3.3 and 6F.3).
    """
    frame = pl.DataFrame({"Price": [0.000123, 1234.56789], "Qty": [3000, -4]})

    payload = export.to_xlsx_bytes(frame, worksheet="Result")

    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        styles = archive.read("xl/styles.xml").decode("utf-8")
    assert "#,##0" not in styles


def test_numeric_values_survive_the_workbook_exactly() -> None:
    frame = pl.DataFrame({"Price": [0.000123, 1234.56789]})

    payload = export.to_xlsx_bytes(frame, worksheet="Result")

    reloaded = parser.parse_tabular_bytes(payload, ".xlsx").frame
    assert reloaded["Price"].to_list() == [0.000123, 1234.56789]


def test_a_date_column_keeps_a_date_format() -> None:
    """Removing the numeric formats must not strip the date one too.

    An Excel date with no format renders as its serial number, which would be
    strictly less faithful than the formatted date.
    """
    frame = pl.DataFrame({"When": [date(2026, 1, 2), date(2026, 3, 4)]})

    payload = export.to_xlsx_bytes(frame, worksheet="Result")

    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        styles = archive.read("xl/styles.xml").decode("utf-8")
    assert "yyyy-mm-dd" in styles


# ---------------------------------------------------------------------------
# 6F.4 Several result tables in one workbook
# ---------------------------------------------------------------------------


def test_a_workbook_holds_one_worksheet_per_table() -> None:
    payload = export.to_workbook_bytes(
        [("Kept", FRAME.head(2)), ("Rejected", FRAME.tail(1))]
    )

    assert _sheet_names(payload) == ["Kept", "Rejected"]


def test_each_worksheet_holds_its_own_table() -> None:
    payload = export.to_workbook_bytes(
        [("Kept", FRAME.head(2)), ("Rejected", FRAME.tail(1))]
    )

    assert _read_sheet(payload, "Kept")["SKU"].to_list() == ["A1", "A2"]
    assert _read_sheet(payload, "Rejected")["SKU"].to_list() == ["A3"]


def test_worksheets_appear_in_the_order_they_were_given() -> None:
    payload = export.to_workbook_bytes(
        [("Third", FRAME), ("First", FRAME), ("Second", FRAME)]
    )

    assert _sheet_names(payload) == ["Third", "First", "Second"]


def test_a_single_table_workbook_is_the_ordinary_one_sheet_export() -> None:
    from_workbook = _sheet_names(export.to_workbook_bytes([("Result", FRAME)]))
    from_single = _sheet_names(export.to_xlsx_bytes(FRAME, worksheet="Result"))

    assert from_workbook == from_single == ["Result"]


def test_a_workbook_with_no_table_is_refused() -> None:
    """Excel will not open a workbook with no worksheet, so neither will this."""
    with pytest.raises(ValueError):
        export.to_workbook_bytes([])


# ---------------------------------------------------------------------------
# 6F.5 Worksheet names: understandable, valid, collision-safe
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("label", "expected"),
    [
        ("Product Master", "Product Master"),
        ("Deduplicated Data", "Deduplicated Data"),
        ("result", "result"),
        # Characters Excel refuses become spaces, and runs of space collapse.
        ("Kept / Rejected", "Kept Rejected"),
        ("A:B\\C/D?E*F[G]H", "A B C D E F G H"),
        # Excel refuses a leading or trailing apostrophe.
        ("'Quoted'", "Quoted"),
        # 31 characters is Excel's limit.
        ("a" * 40, "a" * 31),
        # Nothing usable left: a name is still required.
        ("", export.FALLBACK_WORKSHEET_NAME),
        ("[]", export.FALLBACK_WORKSHEET_NAME),
        ("'''", export.FALLBACK_WORKSHEET_NAME),
    ],
)
def test_a_label_becomes_a_name_excel_accepts(label: str, expected: str) -> None:
    name = export.worksheet_name(label)

    assert name == expected
    assert 1 <= len(name) <= export.MAX_WORKSHEET_NAME_LENGTH
    assert not (set(name) & export.INVALID_WORKSHEET_CHARACTERS)


def test_the_reserved_name_history_is_never_used() -> None:
    """Excel reserves "History"; a workbook using it will not open."""
    assert export.worksheet_name("History").casefold() != "history"
    assert export.worksheet_name("history").casefold() != "history"


def test_two_identical_labels_are_numbered_apart() -> None:
    assert export.worksheet_names(["Result", "Result", "Result"]) == (
        "Result",
        "Result 2",
        "Result 3",
    )


def test_labels_that_differ_only_in_case_are_numbered_apart() -> None:
    """Excel compares worksheet names case-insensitively, so this does too."""
    assert export.worksheet_names(["Result", "RESULT"]) == ("Result", "RESULT 2")


def test_labels_that_collide_only_after_truncation_are_numbered_apart() -> None:
    long_a = "Regional Sales Summary For The" + " North"
    long_b = "Regional Sales Summary For The" + " South"

    names = export.worksheet_names([long_a, long_b])

    assert names[0] != names[1]
    assert all(len(name) <= export.MAX_WORKSHEET_NAME_LENGTH for name in names)


def test_a_numbered_name_still_fits_excels_limit() -> None:
    names = export.worksheet_names(["b" * 40] * 3)

    assert len(set(names)) == 3
    assert all(len(name) <= export.MAX_WORKSHEET_NAME_LENGTH for name in names)


def test_colliding_labels_produce_a_workbook_excel_can_open() -> None:
    """The names are unique in the file itself, not merely in the helper."""
    payload = export.to_workbook_bytes(
        [("Result", FRAME), ("Result", FRAME), ("RESULT", FRAME)]
    )

    names = _sheet_names(payload)
    assert names == ["Result", "Result 2", "RESULT 3"]
    assert len({name.casefold() for name in names}) == 3


# ---------------------------------------------------------------------------
# 6F.6 The download filename convention
# ---------------------------------------------------------------------------


STAMP = datetime(2026, 9, 1, 3, 45, 12, tzinfo=timezone.utc)


def test_the_filename_follows_the_forgexl_convention() -> None:
    assert (
        export.download_filename(
            action_id="product_master_builder",
            output_id="product_master",
            extension="xlsx",
            timestamp=STAMP,
        )
        == "forgexl-product-master-builder-product-master-20260901-034512.xlsx"
    )


def test_a_whole_run_workbook_omits_the_output() -> None:
    assert (
        export.download_filename(
            action_id="product_master_builder",
            extension="xlsx",
            timestamp=STAMP,
        )
        == "forgexl-product-master-builder-20260901-034512.xlsx"
    )


def test_the_same_run_and_output_always_produce_the_same_filename() -> None:
    """A re-download is the same file, so it arrives under the same name."""
    first = export.download_filename(
        action_id="a", output_id="b", extension="csv", timestamp=STAMP
    )
    second = export.download_filename(
        action_id="a", output_id="b", extension="csv", timestamp=STAMP
    )

    assert first == second


def test_the_timestamp_is_rendered_in_utc() -> None:
    """A machine in another timezone must not rename a Run it already recorded."""
    elsewhere = STAMP.astimezone(timezone(timedelta(hours=-7)))

    assert export.download_filename(
        action_id="a", extension="csv", timestamp=elsewhere
    ) == export.download_filename(
        action_id="a", extension="csv", timestamp=STAMP
    )


def test_a_naive_timestamp_is_read_as_utc() -> None:
    assert export.download_filename(
        action_id="a", extension="csv", timestamp=STAMP.replace(tzinfo=None)
    ) == export.download_filename(action_id="a", extension="csv", timestamp=STAMP)


@pytest.mark.parametrize(
    "action_id",
    ["../../escape", "a b/c", "Mixed_Case", "  ", "!!!", "x" * 200],
)
def test_a_filename_can_never_carry_anything_but_safe_characters(
    action_id: str,
) -> None:
    """Nothing in a name can escape a directory or break the header quoting."""
    filename = export.download_filename(
        action_id=action_id, output_id=action_id, extension="csv", timestamp=STAMP
    )

    assert re.fullmatch(r"[a-z0-9-]+\.csv", filename), filename
    assert "/" not in filename and "\\" not in filename
    assert ".." not in filename
    assert '"' not in filename


def test_two_outputs_of_one_run_get_different_filenames() -> None:
    """Downloading both into one folder must not overwrite the first."""
    kept = export.download_filename(
        action_id="split", output_id="kept", extension="csv", timestamp=STAMP
    )
    rejected = export.download_filename(
        action_id="split", output_id="rejected", extension="csv", timestamp=STAMP
    )

    assert kept != rejected


# ---------------------------------------------------------------------------
# 6F.7 Nothing is retained
# ---------------------------------------------------------------------------


def test_the_service_retains_no_export_buffer() -> None:
    """Every call builds its bytes and lets them go; there is no cache to hold."""
    before = {
        name: value
        for name, value in vars(export).items()
        if isinstance(value, (dict, list, set)) and not name.isupper()
    }

    export.to_csv_bytes(FRAME)
    export.to_xlsx_bytes(FRAME, worksheet="Result")
    export.to_workbook_bytes([("Kept", FRAME), ("Rejected", FRAME)])

    after = {
        name: value
        for name, value in vars(export).items()
        if isinstance(value, (dict, list, set)) and not name.isupper()
    }
    assert before == after


def test_repeated_exports_of_one_frame_agree() -> None:
    """Generating on demand must be as deterministic as serving a stored file."""
    assert export.to_csv_bytes(FRAME) == export.to_csv_bytes(FRAME)

    first = parser.parse_tabular_bytes(
        export.to_xlsx_bytes(FRAME, worksheet="Result"), ".xlsx"
    ).frame
    second = parser.parse_tabular_bytes(
        export.to_xlsx_bytes(FRAME, worksheet="Result"), ".xlsx"
    ).frame
    assert first.equals(second)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _read_sheet(payload: bytes, worksheet: str) -> pl.DataFrame:
    """Read one worksheet of a multi-sheet workbook back into a dataframe.

    Uses the same engine the application parses uploads with, so a workbook
    this application could not itself ingest fails here.
    """
    reader = fastexcel.read_excel(payload)
    return reader.load_sheet(worksheet, header_row=0).to_polars()


def _sheet_names(payload: bytes) -> list[str]:
    """Worksheet names in workbook order, read out of the workbook part."""
    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        workbook = archive.read("xl/workbook.xml").decode("utf-8")
    return [
        html.unescape(name)
        for name in re.findall(r'<sheet name="([^"]*)"', workbook)
    ]