"""End-to-end spreadsheet regression tests (build plan 6H.3, 6H.4, 6H.6).

Build plan 6H.4 names the path these tests walk, and they walk all of it:

    create fixture in memory
            ↓
    submit upload
            ↓
    execute Action
            ↓
    retrieve preview
            ↓
    request export
            ↓
    read export
            ↓
    assert expected result

Every dataset is generated by `tests/fixtures/spreadsheets.py`, so no file
picker, no saved workbook and no company spreadsheet is involved (6H.1, 6H.8).
Every expected output comes from `tests/fixtures/action_cases.py`, where it is
stated in plain Python rather than produced by the code under test (6H.3).

Each case runs twice — once uploaded as CSV, once as XLSX — because a defect
in one reader is invisible to a suite that only exercises the other. Exports
are read back with ForgeXL's *own* parser, so an export the application could
not itself ingest fails here (6H.6).
"""

from __future__ import annotations

import fastexcel
import polars as pl
import pytest

from app.services import parser

from tests.fixtures import action_cases, spreadsheets as fx
from tests.fixtures.action_cases import ActionCase
from tests.helpers import normalise_rows, upload_file

CASE_IDS = action_cases.CASE_IDS


# ---------------------------------------------------------------------------
# Driving the real API
# ---------------------------------------------------------------------------


def run_case(client, case: ActionCase, extension: str) -> dict:
    """Submit `case`'s fixture in `extension` and return the run manifest.

    The fixture bytes are built here and handed straight to the request, which
    is what build plan 6H.4's first two steps mean by "create fixture in
    memory" then "submit upload": nothing is saved and reopened on the way.
    """
    response = client.post(
        "/api/runs",
        data={"action_id": case.action_id},
        files={
            case.slot_id: upload_file(
                case.source.filename(extension), case.source.payload(extension)
            )
        },
    )
    assert response.status_code == 200, response.text
    return response.json()


def preview_rows(client, run_id: str, output_id: str) -> list[list]:
    """Every row of an output, paged through the preview endpoint.

    Paged rather than fetched at once because the endpoint caps a page at 500
    rows; walking the pages is also what a client does, so this exercises the
    paging rather than avoiding it.
    """
    rows: list[list] = []
    offset = 0
    while True:
        response = client.get(
            f"/api/runs/{run_id}/outputs/{output_id}/preview",
            params={"offset": offset, "limit": 500},
        )
        assert response.status_code == 200, response.text
        page = response.json()
        rows.extend(page["rows"])
        offset += len(page["rows"])
        if offset >= page["total_rows"] or not page["rows"]:
            return rows


def download(client, run_id: str, output_id: str, export_format: str) -> bytes:
    response = client.get(
        f"/api/runs/{run_id}/outputs/{output_id}/download/{export_format}"
    )
    assert response.status_code == 200, response.text
    return response.content


def reread_export(payload: bytes, export_format: str) -> pl.DataFrame:
    """Read a downloaded export back with ForgeXL's own parser.

    Using the application's parser rather than a second reader is deliberate:
    an export ForgeXL could produce but not ingest would be a real defect, and
    this is what catches it (build plan 6H.6).
    """
    return parser.parse_tabular_bytes(payload, f".{export_format}").frame


def output_metadata(manifest: dict, output_id: str) -> dict:
    for output in manifest["outputs"]:
        if output["id"] == output_id:
            return output
    raise AssertionError(f"{output_id} not among {manifest['outputs']}")


# ---------------------------------------------------------------------------
# 6H.3 / 6H.4 — the complete path, for every known-outcome case
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("case", action_cases.CASES, ids=CASE_IDS)
@pytest.mark.parametrize("extension", fx.UPLOAD_EXTENSIONS)
def test_a_fixture_runs_to_the_expected_result(
    client, case: ActionCase, extension: str
) -> None:
    """Known input, known Action, known expected output (6H.3)."""
    manifest = run_case(client, case, extension)

    assert manifest["status"] == "succeeded"
    assert manifest["action"]["id"] == case.action_id

    output = output_metadata(manifest, case.output_id)
    assert output["columns"] == list(case.expected_columns)
    assert output["row_count"] == case.expected_row_count
    assert output["input_row_count"] == case.source.row_count


@pytest.mark.parametrize("case", action_cases.CASES, ids=CASE_IDS)
@pytest.mark.parametrize("extension", fx.UPLOAD_EXTENSIONS)
def test_the_preview_serves_the_expected_rows(
    client, case: ActionCase, extension: str
) -> None:
    """Step 4: retrieve preview, and check it against the expected output."""
    manifest = run_case(client, case, extension)

    rows = preview_rows(client, manifest["run_id"], case.output_id)

    assert normalise_rows(rows) == normalise_rows(case.expected.rows)


@pytest.mark.parametrize("case", action_cases.CASES, ids=CASE_IDS)
@pytest.mark.parametrize("extension", fx.UPLOAD_EXTENSIONS)
@pytest.mark.parametrize("export_format", ("csv", "xlsx"))
def test_the_export_reads_back_as_the_expected_result(
    client, case: ActionCase, extension: str, export_format: str
) -> None:
    """Steps 5-7: request the export, read it back, assert the result.

    The whole build plan 6H.4 pipeline closes here — the bytes a user would
    download are parsed again by the application and compared against the
    expected output the fixture states.
    """
    manifest = run_case(client, case, extension)

    frame = reread_export(
        download(client, manifest["run_id"], case.output_id, export_format),
        export_format,
    )

    assert tuple(frame.columns) == case.expected_columns
    assert normalise_rows(frame.rows()) == normalise_rows(case.expected.rows)


@pytest.mark.parametrize("case", action_cases.CASES, ids=CASE_IDS)
def test_a_csv_upload_and_an_xlsx_upload_reach_the_same_result(
    client, case: ActionCase
) -> None:
    """One fixture, two upload paths, one answer.

    A reader that quietly disagreed with the other would show up here rather
    than in whichever format a developer happened to test by hand.
    """
    from_csv = run_case(client, case, fx.CSV_EXTENSION)
    from_xlsx = run_case(client, case, fx.XLSX_EXTENSION)

    assert from_csv["metrics"] == from_xlsx["metrics"]
    assert from_csv["audit"]["rows_affected"] == from_xlsx["audit"]["rows_affected"]

    csv_rows = preview_rows(client, from_csv["run_id"], case.output_id)
    xlsx_rows = preview_rows(client, from_xlsx["run_id"], case.output_id)
    assert normalise_rows(csv_rows) == normalise_rows(xlsx_rows)


@pytest.mark.parametrize("case", action_cases.CASES, ids=CASE_IDS)
@pytest.mark.parametrize("extension", fx.UPLOAD_EXTENSIONS)
def test_the_action_reports_the_rows_it_affected(
    client, case: ActionCase, extension: str
) -> None:
    """Build plan 6E.5, asserted against the fixture's own arithmetic."""
    manifest = run_case(client, case, extension)

    assert manifest["audit"]["rows_affected"] == case.expected_rows_affected
    assert manifest["metrics"]["input_rows"] == case.source.row_count
    assert manifest["metrics"]["output_rows"] == case.expected_row_count


# ---------------------------------------------------------------------------
# 6H.6 — XLSX round-trip compatibility
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("case", action_cases.CASES, ids=CASE_IDS)
@pytest.mark.parametrize("extension", fx.UPLOAD_EXTENSIONS)
def test_the_exported_workbook_is_readable_and_correctly_named(
    client, case: ActionCase, extension: str
) -> None:
    """6H.6: reopen the export, check the worksheet, the headers, the values."""
    manifest = run_case(client, case, extension)
    payload = download(client, manifest["run_id"], case.output_id, "xlsx")

    reader = fastexcel.read_excel(payload)
    assert list(reader.sheet_names) == [case.output_label]

    sheet = reader.load_sheet(case.output_label, header_row=0).to_polars()
    assert tuple(sheet.columns) == case.expected_columns
    assert normalise_rows(sheet.rows()) == normalise_rows(case.expected.rows)


def test_an_exported_column_name_that_looks_like_a_formula_stays_text(
    client,
) -> None:
    """Build plan section 16, through the whole pipeline.

    `=Not A Formula` is a column name in the upload. If any stage wrote it as
    a formula, it would come back as a computed value instead of the name.
    """
    case = next(
        item
        for item in action_cases.DEDUPLICATION_CASES
        if item.source is fx.UNUSUAL_COLUMN_NAMES
    )
    manifest = run_case(client, case, fx.CSV_EXTENSION)

    payload = download(client, manifest["run_id"], case.output_id, "xlsx")
    sheet = fastexcel.read_excel(payload).load_sheet(
        case.output_label, header_row=0
    ).to_polars()

    assert "=Not A Formula" in sheet.columns


def test_accented_text_survives_the_whole_round_trip(client) -> None:
    """Upload → Action → export → reopen, without a character changing."""
    case = next(
        item
        for item in action_cases.DEDUPLICATION_CASES
        if item.source is fx.ACCENTED_TEXT
    )

    for extension in fx.UPLOAD_EXTENSIONS:
        manifest = run_case(client, case, extension)
        for export_format in ("csv", "xlsx"):
            frame = reread_export(
                download(client, manifest["run_id"], case.output_id, export_format),
                export_format,
            )
            producers = frame["Producer"].to_list()
            assert producers == [
                "Château Margaux",
                "Chateau Margaux",
                "Domaine Père et Fils",
                "Domaine Pere et Fils",
                "Bodegas Muñoz",
            ], f"{extension} -> {export_format}"


def test_unicode_text_survives_the_whole_round_trip(client) -> None:
    case = next(
        item
        for item in action_cases.DEDUPLICATION_CASES
        if item.source is fx.UNICODE_TEXT
    )

    for extension in fx.UPLOAD_EXTENSIONS:
        manifest = run_case(client, case, extension)
        for export_format in ("csv", "xlsx"):
            frame = reread_export(
                download(client, manifest["run_id"], case.output_id, export_format),
                export_format,
            )
            assert frame["Producer"].to_list() == [
                "東京商事",
                "Ζορμπάς",
                "Пётр Смирнов",
                "O'Brien & Sons, Ltd.",
                "‘smart quotes’",
            ], f"{extension} -> {export_format}"


def test_blank_rows_and_cells_survive_the_whole_round_trip(client) -> None:
    """Build plan section 3.3: no row is dropped and no blank is invented."""
    case = next(
        item
        for item in action_cases.DEDUPLICATION_CASES
        if item.source is fx.BLANK_ROWS
    )

    for extension in fx.UPLOAD_EXTENSIONS:
        manifest = run_case(client, case, extension)
        frame = reread_export(
            download(client, manifest["run_id"], case.output_id, "csv"), "csv"
        )
        # Four rows survive: the two identical blank rows deduplicate to one.
        assert frame.height == 4
        assert frame.rows()[1] == (None, None, None)


# ---------------------------------------------------------------------------
# 6H.2 — the larger dataset, end to end
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("extension", fx.UPLOAD_EXTENSIONS)
def test_a_large_dataset_deduplicates_to_the_expected_result(
    client, extension: str
) -> None:
    """25,000 generated rows through the whole pipeline.

    Large enough that the answer could not be a coincidence of a handful of
    rows, and every value is still checked — the expected output is closed
    form because the generator repeats with a known period.
    """
    case = action_cases.large_deduplication_case()

    manifest = run_case(client, case, extension)
    output = output_metadata(manifest, case.output_id)

    assert output["input_row_count"] == action_cases.LARGE_ROW_COUNT
    assert output["row_count"] == fx.PRODUCT_POOL

    frame = reread_export(
        download(client, manifest["run_id"], case.output_id, "csv"), "csv"
    )
    assert normalise_rows(frame.rows()) == normalise_rows(case.expected.rows)


def test_a_large_dataset_builds_the_expected_product_master(client) -> None:
    case = action_cases.large_product_master_case()

    manifest = run_case(client, case, fx.CSV_EXTENSION)
    output = output_metadata(manifest, case.output_id)

    assert output["columns"] == list(case.expected_columns)
    assert output["row_count"] == fx.PRODUCT_POOL
    assert manifest["audit"]["rows_affected"] == case.expected_rows_affected

    frame = reread_export(
        download(client, manifest["run_id"], case.output_id, "xlsx"), "xlsx"
    )
    assert normalise_rows(frame.rows()) == normalise_rows(case.expected.rows)


def test_a_large_dataset_pages_through_the_preview_completely(client) -> None:
    """The preview must serve every row of a large result, page by page."""
    case = action_cases.large_deduplication_case()
    manifest = run_case(client, case, fx.CSV_EXTENSION)

    rows = preview_rows(client, manifest["run_id"], case.output_id)

    assert len(rows) == fx.PRODUCT_POOL
    assert normalise_rows(rows) == normalise_rows(case.expected.rows)


# ---------------------------------------------------------------------------
# The mixed numeric/text fixture, end to end
# ---------------------------------------------------------------------------


def test_a_mixed_column_uploaded_as_csv_reaches_the_export_intact(client) -> None:
    """Every value of a mixed column survives upload, Action and export.

    The CSV path types the column as text, which loses nothing: `n/a` arrives
    in the downloaded file as `n/a`.
    """
    manifest = run_case(
        client,
        action_cases._deduplication_case(fx.MIXED_VALUES),
        fx.CSV_EXTENSION,
    )

    frame = reread_export(
        download(client, manifest["run_id"], "deduplicated_data", "csv"), "csv"
    )

    assert frame["Value"].to_list() == ["10", "n/a", "2.5", None, "-3", "0"]
