"""Export service tests (build plan 3.10, 6D.7 and 6F).

Proves the generated bytes are genuinely readable files, not merely bytes with
the right name — and that generating them writes nothing to the filesystem.

Until Phase 6D these tests read three artifacts back off disk. The exports are
built in memory now, so each assertion is made against the bytes the service
returned instead of against a file it wrote.

Phase 6F adds the rest of the export contract: the workbook is assembled with
no temporary file at all, an Action's several tables become several worksheets,
worksheet names are valid and unique, and downloads are named by the ForgeXL
convention.
"""

from __future__ import annotations

import html
import io
import re
import tempfile
import zipfile
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

import fastexcel
import polars as pl
import pytest

from app.errors import ExportTooLargeError
from app.services import export, parser

FRAME = pl.DataFrame(
    {
        "SKU": ["A1", "A2", "A3"],
        "Producer": ["Château Margaux", "Bodegas Muñoz", None],
        "Volume": [750, 1500, 375],
    }
)


# ---------------------------------------------------------------------------
# CSV (build plan 6D.7; 6F.1 formalises the download contract)
# ---------------------------------------------------------------------------


def test_the_csv_export_round_trips() -> None:
    payload = export.to_csv_bytes(FRAME)

    reloaded = pl.read_csv(io.BytesIO(payload))

    assert reloaded.columns == FRAME.columns
    assert reloaded.height == 3
    assert reloaded["Producer"].to_list() == [
        "Château Margaux",
        "Bodegas Muñoz",
        None,
    ]


def test_the_csv_header_is_the_frame_column_order() -> None:
    payload = export.to_csv_bytes(FRAME)

    assert payload.decode("utf-8").splitlines()[0] == "SKU,Producer,Volume"


def test_an_empty_result_still_produces_a_header_row() -> None:
    payload = export.to_csv_bytes(FRAME.head(0))

    assert payload.decode("utf-8").strip() == "SKU,Producer,Volume"


# ---------------------------------------------------------------------------
# XLSX
# ---------------------------------------------------------------------------


def test_the_xlsx_export_is_a_real_workbook_that_round_trips() -> None:
    payload = export.to_xlsx_bytes(FRAME, worksheet="product_master")

    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        assert "xl/workbook.xml" in archive.namelist()

    # Read back through the application's own reader: an export this
    # application could not itself ingest fails here.
    reloaded = parser.parse_tabular_bytes(payload, ".xlsx").frame
    assert reloaded.columns == FRAME.columns
    assert reloaded.height == 3
    assert reloaded["SKU"].to_list() == ["A1", "A2", "A3"]
    assert reloaded["Volume"].to_list() == [750, 1500, 375]


def test_accented_values_survive_the_excel_round_trip() -> None:
    payload = export.to_xlsx_bytes(FRAME, worksheet="product_master")

    reloaded = parser.parse_tabular_bytes(payload, ".xlsx").frame

    assert reloaded["Producer"].to_list()[:2] == ["Château Margaux", "Bodegas Muñoz"]


def test_the_worksheet_is_named_after_the_output() -> None:
    payload = export.to_xlsx_bytes(FRAME, worksheet="product_master")

    assert parser.parse_tabular_bytes(payload, ".xlsx").worksheet == "product_master"


@pytest.mark.parametrize(
    ("output_id", "expected"),
    [
        ("result", "result"),
        ("product_master", "product_master"),
        ("a" * 40, "a" * 31),
    ],
)
def test_a_worksheet_name_never_exceeds_excels_limit(
    output_id: str, expected: str
) -> None:
    assert export.worksheet_name(output_id) == expected
    assert len(export.worksheet_name(output_id)) <= 31


def test_an_empty_result_still_produces_a_valid_workbook() -> None:
    payload = export.to_xlsx_bytes(FRAME.head(0), worksheet="result")

    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        assert "xl/workbook.xml" in archive.namelist()


# ---------------------------------------------------------------------------
# Format dispatch
# ---------------------------------------------------------------------------


def test_to_bytes_dispatches_on_the_requested_format() -> None:
    csv_payload = export.to_bytes(FRAME, export.CSV_FORMAT, name="result")
    xlsx_payload = export.to_bytes(FRAME, export.XLSX_FORMAT, name="result")

    assert csv_payload == export.to_csv_bytes(FRAME)
    assert xlsx_payload.startswith(b"PK")


def test_an_unknown_format_is_refused() -> None:
    with pytest.raises(ValueError):
        export.to_bytes(FRAME, "parquet", name="result")


def test_the_offered_formats_are_csv_then_xlsx() -> None:
    assert export.EXPORT_FORMATS == ("csv", "xlsx")


# ---------------------------------------------------------------------------
# 6D.7 Nothing is written
# ---------------------------------------------------------------------------


def test_generating_an_export_writes_nothing(
    tmp_path: Path, quarantine: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Build plan 6D: a Run needs no ``working/`` or ``exports/`` directory."""
    empty = tmp_path / "cwd"
    empty.mkdir()
    monkeypatch.chdir(empty)

    export.to_csv_bytes(FRAME)
    export.to_xlsx_bytes(FRAME, worksheet="result")

    assert list(empty.iterdir()) == []
    assert list(quarantine.rglob("*")) == []


def test_the_service_no_longer_writes_artifacts() -> None:
    """The path-writing API is gone, not merely unused."""
    assert not hasattr(export, "write_output")
    assert not hasattr(export, "write_parquet")
    assert not hasattr(export, "write_csv")
    assert not hasattr(export, "write_xlsx")


# ---------------------------------------------------------------------------
# 6F.2 The workbook is built in memory — not spooled through /tmp
# ---------------------------------------------------------------------------


def test_the_workbook_is_opened_in_memory() -> None:
    """xlsxwriter must be told not to use the OS temporary directory.

    Its default is to spool the workbook's parts through ``tempfile``. Build
    plan 6F.2 asks for an in-memory binary buffer, so the option is asserted
    directly as well as observed below.
    """
    assert export.WORKBOOK_OPTIONS["in_memory"] is True


def test_generating_a_workbook_creates_no_temporary_file(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Build plan 6F.2: nothing reaches a disk, including ``/tmp``."""
    created: list[str] = []
    real_mkstemp = tempfile.mkstemp
    real_named = tempfile.NamedTemporaryFile

    def spy_mkstemp(*args, **kwargs):
        handle, path = real_mkstemp(*args, **kwargs)
        created.append(path)
        return handle, path

    def spy_named(*args, **kwargs):
        opened = real_named(*args, **kwargs)
        created.append(getattr(opened, "name", "?"))
        return opened

    monkeypatch.setattr(tempfile, "mkstemp", spy_mkstemp)
    monkeypatch.setattr(tempfile, "NamedTemporaryFile", spy_named)

    export.to_xlsx_bytes(FRAME, worksheet="Result")
    export.to_workbook_bytes([("Kept", FRAME), ("Rejected", FRAME.head(1))])

    assert created == []


def test_a_cell_beginning_with_an_equals_sign_stays_text() -> None:
    """Build plan section 16: an uploaded value is never written as a formula."""
    frame = pl.DataFrame({"Note": ["=SUM(A1:A9)", "plain"]})

    payload = export.to_xlsx_bytes(frame, worksheet="Result")

    assert export.WORKBOOK_OPTIONS["strings_to_formulas"] is False
    assert parser.parse_tabular_bytes(payload, ".xlsx").frame[
        "Note"
    ].to_list() == ["=SUM(A1:A9)", "plain"]


# ---------------------------------------------------------------------------
# 6F.3 Sensible cell values
# ---------------------------------------------------------------------------


def test_numeric_columns_carry_no_display_format() -> None:
    """A small value must not be shown as 0.000, nor a large one regrouped.

    Polars applies ``#,##0.000`` to every numeric column by default. The stored
    value stays exact either way, but what Excel *shows* is what a reader
    trusts, so numbers are presented exactly as the data holds them
    (build plan 3.3 and 6F.3).
    """
    frame = pl.DataFrame({"Price": [0.000123, 1234.56789], "Qty": [3000, -4]})

    payload = export.to_xlsx_bytes(frame, worksheet="Result")

    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        styles = archive.read("xl/styles.xml").decode("utf-8")
    assert "#,##0" not in styles


def test_numeric_values_survive_the_workbook_exactly() -> None:
    frame = pl.DataFrame({"Price": [0.000123, 1234.56789]})

    payload = export.to_xlsx_bytes(frame, worksheet="Result")

    reloaded = parser.parse_tabular_bytes(payload, ".xlsx").frame
    assert reloaded["Price"].to_list() == [0.000123, 1234.56789]


def test_a_date_column_keeps_a_date_format() -> None:
    """Removing the numeric formats must not strip the date one too.

    An Excel date with no format renders as its serial number, which would be
    strictly less faithful than the formatted date.
    """
    frame = pl.DataFrame({"When": [date(2026, 1, 2), date(2026, 3, 4)]})

    payload = export.to_xlsx_bytes(frame, worksheet="Result")

    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        styles = archive.read("xl/styles.xml").decode("utf-8")
    assert "yyyy-mm-dd" in styles


# ---------------------------------------------------------------------------
# 6F.4 Several result tables in one workbook
# ---------------------------------------------------------------------------


def test_a_workbook_holds_one_worksheet_per_table() -> None:
    payload = export.to_workbook_bytes(
        [("Kept", FRAME.head(2)), ("Rejected", FRAME.tail(1))]
    )

    assert _sheet_names(payload) == ["Kept", "Rejected"]


def test_each_worksheet_holds_its_own_table() -> None:
    payload = export.to_workbook_bytes(
        [("Kept", FRAME.head(2)), ("Rejected", FRAME.tail(1))]
    )

    assert _read_sheet(payload, "Kept")["SKU"].to_list() == ["A1", "A2"]
    assert _read_sheet(payload, "Rejected")["SKU"].to_list() == ["A3"]


def test_worksheets_appear_in_the_order_they_were_given() -> None:
    payload = export.to_workbook_bytes(
        [("Third", FRAME), ("First", FRAME), ("Second", FRAME)]
    )

    assert _sheet_names(payload) == ["Third", "First", "Second"]


def test_a_single_table_workbook_is_the_ordinary_one_sheet_export() -> None:
    from_workbook = _sheet_names(export.to_workbook_bytes([("Result", FRAME)]))
    from_single = _sheet_names(export.to_xlsx_bytes(FRAME, worksheet="Result"))

    assert from_workbook == from_single == ["Result"]


def test_a_workbook_with_no_table_is_refused() -> None:
    """Excel will not open a workbook with no worksheet, so neither will this."""
    with pytest.raises(ValueError):
        export.to_workbook_bytes([])


# ---------------------------------------------------------------------------
# 6F.5 Worksheet names: understandable, valid, collision-safe
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("label", "expected"),
    [
        ("Product Master", "Product Master"),
        ("Deduplicated Data", "Deduplicated Data"),
        ("result", "result"),
        # Characters Excel refuses become spaces, and runs of space collapse.
        ("Kept / Rejected", "Kept Rejected"),
        ("A:B\\C/D?E*F[G]H", "A B C D E F G H"),
        # Excel refuses a leading or trailing apostrophe.
        ("'Quoted'", "Quoted"),
        # 31 characters is Excel's limit.
        ("a" * 40, "a" * 31),
        # Nothing usable left: a name is still required.
        ("", export.FALLBACK_WORKSHEET_NAME),
        ("[]", export.FALLBACK_WORKSHEET_NAME),
        ("'''", export.FALLBACK_WORKSHEET_NAME),
    ],
)
def test_a_label_becomes_a_name_excel_accepts(label: str, expected: str) -> None:
    name = export.worksheet_name(label)

    assert name == expected
    assert 1 <= len(name) <= export.MAX_WORKSHEET_NAME_LENGTH
    assert not (set(name) & export.INVALID_WORKSHEET_CHARACTERS)


def test_the_reserved_name_history_is_never_used() -> None:
    """Excel reserves "History"; a workbook using it will not open."""
    assert export.worksheet_name("History").casefold() != "history"
    assert export.worksheet_name("history").casefold() != "history"


def test_two_identical_labels_are_numbered_apart() -> None:
    assert export.worksheet_names(["Result", "Result", "Result"]) == (
        "Result",
        "Result 2",
        "Result 3",
    )


def test_labels_that_differ_only_in_case_are_numbered_apart() -> None:
    """Excel compares worksheet names case-insensitively, so this does too."""
    assert export.worksheet_names(["Result", "RESULT"]) == ("Result", "RESULT 2")


def test_labels_that_collide_only_after_truncation_are_numbered_apart() -> None:
    long_a = "Regional Sales Summary For The" + " North"
    long_b = "Regional Sales Summary For The" + " South"

    names = export.worksheet_names([long_a, long_b])

    assert names[0] != names[1]
    assert all(len(name) <= export.MAX_WORKSHEET_NAME_LENGTH for name in names)


def test_a_numbered_name_still_fits_excels_limit() -> None:
    names = export.worksheet_names(["b" * 40] * 3)

    assert len(set(names)) == 3
    assert all(len(name) <= export.MAX_WORKSHEET_NAME_LENGTH for name in names)


def test_colliding_labels_produce_a_workbook_excel_can_open() -> None:
    """The names are unique in the file itself, not merely in the helper."""
    payload = export.to_workbook_bytes(
        [("Result", FRAME), ("Result", FRAME), ("RESULT", FRAME)]
    )

    names = _sheet_names(payload)
    assert names == ["Result", "Result 2", "RESULT 3"]
    assert len({name.casefold() for name in names}) == 3


# ---------------------------------------------------------------------------
# 6F.6 The download filename convention
# ---------------------------------------------------------------------------


STAMP = datetime(2026, 9, 1, 3, 45, 12, tzinfo=timezone.utc)


def test_the_filename_follows_the_forgexl_convention() -> None:
    assert (
        export.download_filename(
            action_id="product_master_builder",
            output_id="product_master",
            extension="xlsx",
            timestamp=STAMP,
        )
        == "forgexl-product-master-builder-product-master-20260901-034512.xlsx"
    )


def test_a_whole_run_workbook_omits_the_output() -> None:
    assert (
        export.download_filename(
            action_id="product_master_builder",
            extension="xlsx",
            timestamp=STAMP,
        )
        == "forgexl-product-master-builder-20260901-034512.xlsx"
    )


def test_the_same_run_and_output_always_produce_the_same_filename() -> None:
    """A re-download is the same file, so it arrives under the same name."""
    first = export.download_filename(
        action_id="a", output_id="b", extension="csv", timestamp=STAMP
    )
    second = export.download_filename(
        action_id="a", output_id="b", extension="csv", timestamp=STAMP
    )

    assert first == second


def test_the_timestamp_is_rendered_in_utc() -> None:
    """A machine in another timezone must not rename a Run it already recorded."""
    elsewhere = STAMP.astimezone(timezone(timedelta(hours=-7)))

    assert export.download_filename(
        action_id="a", extension="csv", timestamp=elsewhere
    ) == export.download_filename(
        action_id="a", extension="csv", timestamp=STAMP
    )


def test_a_naive_timestamp_is_read_as_utc() -> None:
    assert export.download_filename(
        action_id="a", extension="csv", timestamp=STAMP.replace(tzinfo=None)
    ) == export.download_filename(action_id="a", extension="csv", timestamp=STAMP)


@pytest.mark.parametrize(
    "action_id",
    ["../../escape", "a b/c", "Mixed_Case", "  ", "!!!", "x" * 200],
)
def test_a_filename_can_never_carry_anything_but_safe_characters(
    action_id: str,
) -> None:
    """Nothing in a name can escape a directory or break the header quoting."""
    filename = export.download_filename(
        action_id=action_id, output_id=action_id, extension="csv", timestamp=STAMP
    )

    assert re.fullmatch(r"[a-z0-9-]+\.csv", filename), filename
    assert "/" not in filename and "\\" not in filename
    assert ".." not in filename
    assert '"' not in filename


def test_two_outputs_of_one_run_get_different_filenames() -> None:
    """Downloading both into one folder must not overwrite the first."""
    kept = export.download_filename(
        action_id="split", output_id="kept", extension="csv", timestamp=STAMP
    )
    rejected = export.download_filename(
        action_id="split", output_id="rejected", extension="csv", timestamp=STAMP
    )

    assert kept != rejected


# ---------------------------------------------------------------------------
# 6F.7 Nothing is retained
# ---------------------------------------------------------------------------


def test_the_service_retains_no_export_buffer() -> None:
    """Every call builds its bytes and lets them go; there is no cache to hold."""
    before = {
        name: value
        for name, value in vars(export).items()
        if isinstance(value, (dict, list, set)) and not name.isupper()
    }

    export.to_csv_bytes(FRAME)
    export.to_xlsx_bytes(FRAME, worksheet="Result")
    export.to_workbook_bytes([("Kept", FRAME), ("Rejected", FRAME)])

    after = {
        name: value
        for name, value in vars(export).items()
        if isinstance(value, (dict, list, set)) and not name.isupper()
    }
    assert before == after


def test_repeated_exports_of_one_frame_agree() -> None:
    """Generating on demand must be as deterministic as serving a stored file."""
    assert export.to_csv_bytes(FRAME) == export.to_csv_bytes(FRAME)

    first = parser.parse_tabular_bytes(
        export.to_xlsx_bytes(FRAME, worksheet="Result"), ".xlsx"
    ).frame
    second = parser.parse_tabular_bytes(
        export.to_xlsx_bytes(FRAME, worksheet="Result"), ".xlsx"
    ).frame
    assert first.equals(second)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _read_sheet(payload: bytes, worksheet: str) -> pl.DataFrame:
    """Read one worksheet of a multi-sheet workbook back into a dataframe.

    Uses the same engine the application parses uploads with, so a workbook
    this application could not itself ingest fails here.
    """
    reader = fastexcel.read_excel(payload)
    return reader.load_sheet(worksheet, header_row=0).to_polars()


def _sheet_names(payload: bytes) -> list[str]:
    """Worksheet names in workbook order, read out of the workbook part."""
    with zipfile.ZipFile(io.BytesIO(payload)) as archive:
        workbook = archive.read("xl/workbook.xml").decode("utf-8")
    return [
        html.unescape(name)
        for name in re.findall(r'<sheet name="([^"]*)"', workbook)
    ]

# ---------------------------------------------------------------------------
# XLSX format capacity (build plan 7B, 7F; section 3.3)
#
# Three limits belong to the file format, and before Phase 7 each reached the
# user badly. An over-long cell was silently truncated by xlsxwriter, which is
# section 3.3's "silently convert invalid data into valid-looking data"; an
# over-large grid raised a Polars error nothing caught, which the API returned
# as a bare 500. `check_fits_worksheet` measures first and refuses with a
# structured error naming the limit.
# ---------------------------------------------------------------------------


def test_a_cell_at_the_character_limit_is_written_whole() -> None:
    """The boundary from the side that must keep working."""
    at_limit = "x" * export.MAX_CELL_CHARACTERS
    frame = pl.DataFrame({"note": [at_limit]})

    payload = export.to_xlsx_bytes(frame, worksheet="Result")

    assert parser.parse_tabular_bytes(payload, ".xlsx").frame["note"][0] == at_limit


def test_a_cell_over_the_character_limit_is_refused_not_truncated() -> None:
    """One character past the limit, which is where the truncation used to be.

    Verified as a real truncation, not a theoretical one: xlsxwriter writes
    32,767 characters and returns a code Polars does not check, so the file
    opened cleanly and the value was quietly shorter than the one uploaded.
    """
    too_long = "x" * (export.MAX_CELL_CHARACTERS + 1)
    frame = pl.DataFrame({"note": [too_long]})

    with pytest.raises(ExportTooLargeError) as raised:
        export.to_xlsx_bytes(frame, worksheet="Result")

    error = raised.value
    assert error.code == "EXPORT_TOO_LARGE"
    assert error.http_status == 422
    assert error.details["limit"] == "cell_characters"
    assert error.details["column"] == "note"
    assert error.details["actual"] == export.MAX_CELL_CHARACTERS + 1
    assert error.details["maximum"] == export.MAX_CELL_CHARACTERS
    # The message points at the format that has no such limit.
    assert "CSV" in error.message


def test_the_refusal_names_the_column_the_long_value_is_in() -> None:
    """A user with a wide result needs to know where to look."""
    frame = pl.DataFrame(
        {
            "sku": ["A1"],
            "short note": ["fine"],
            "long note": ["x" * (export.MAX_CELL_CHARACTERS + 10)],
        }
    )

    with pytest.raises(ExportTooLargeError) as raised:
        export.to_xlsx_bytes(frame, worksheet="Result")

    assert raised.value.details["column"] == "long note"


def test_the_same_over_long_value_exports_as_csv_without_complaint() -> None:
    """CSV has no cell limit, so the refusal above is about XLSX alone.

    This is what makes the refusal acceptable rather than a dead end: the user
    is not blocked from their data, only from one representation of it.
    """
    too_long = "x" * (export.MAX_CELL_CHARACTERS + 5_000)
    frame = pl.DataFrame({"note": [too_long]})

    payload = export.to_csv_bytes(frame)

    assert parser.parse_tabular_bytes(payload, ".csv").frame["note"][0] == too_long


def test_characters_are_counted_not_bytes() -> None:
    """Excel counts characters, and so does the guard.

    An accented value is one character per letter however many bytes it takes,
    so a value comfortably inside the limit must not be refused for the size of
    its UTF-8 encoding.
    """
    # Well over the limit in bytes (3 bytes each), well under it in characters.
    multibyte = "é" * (export.MAX_CELL_CHARACTERS - 1)
    assert len(multibyte.encode("utf-8")) > export.MAX_CELL_CHARACTERS

    payload = export.to_xlsx_bytes(pl.DataFrame({"note": [multibyte]}), worksheet="R")

    assert parser.parse_tabular_bytes(payload, ".xlsx").frame["note"][0] == multibyte


def test_a_frame_wider_than_the_worksheet_is_refused_with_its_numbers() -> None:
    """Excel's grid is 16,384 columns; past it Polars raises and nothing caught it."""
    frame = pl.DataFrame({f"c{index}": [1] for index in range(
        export.MAX_WORKSHEET_COLUMNS + 1
    )})

    with pytest.raises(ExportTooLargeError) as raised:
        export.to_xlsx_bytes(frame, worksheet="Result")

    assert raised.value.details["limit"] == "columns"
    assert raised.value.details["actual"] == export.MAX_WORKSHEET_COLUMNS + 1
    assert raised.value.details["maximum"] == export.MAX_WORKSHEET_COLUMNS


def test_a_frame_at_the_column_limit_is_written() -> None:
    """The boundary, from the side that must work. Deliberately the exact width."""
    frame = pl.DataFrame(
        {f"c{index}": [1] for index in range(export.MAX_WORKSHEET_COLUMNS)}
    )

    payload = export.to_xlsx_bytes(frame, worksheet="Result")

    assert parser.parse_tabular_bytes(payload, ".xlsx").frame.width == (
        export.MAX_WORKSHEET_COLUMNS
    )


def test_a_frame_taller_than_the_worksheet_is_refused() -> None:
    """The row limit, checked without building a million-row frame.

    The guard reads `frame.height`, so a lazily-constructed frame of the right
    height proves the rule at the cost of the rows it actually needs. Building
    1,048,576 real rows to assert an integer comparison would add seconds to
    the suite for nothing.
    """
    too_tall = pl.select(
        pl.int_range(0, export.MAX_WORKSHEET_ROWS + 1, eager=True).alias("n")
    )
    assert too_tall.height == export.MAX_WORKSHEET_ROWS + 1

    with pytest.raises(ExportTooLargeError) as raised:
        export.to_xlsx_bytes(too_tall, worksheet="Result")

    assert raised.value.details["limit"] == "rows"
    assert raised.value.details["maximum"] == export.MAX_WORKSHEET_ROWS


def test_the_limits_are_excels_own_numbers() -> None:
    """Pinned, because they are facts about the format and not preferences."""
    assert export.MAX_WORKSHEET_ROWS == 1_048_575  # 1,048,576 less the header
    assert export.MAX_WORKSHEET_COLUMNS == 16_384  # column XFD
    assert export.MAX_CELL_CHARACTERS == 32_767


def test_a_workbook_is_never_half_built_before_a_table_is_refused() -> None:
    """Every table is checked before any is written (build plan 6F.4).

    A workbook whose second sheet is impossible must fail as a whole, not
    produce a one-sheet file that looks complete.
    """
    fits = pl.DataFrame({"a": [1]})
    does_not = pl.DataFrame({"note": ["x" * (export.MAX_CELL_CHARACTERS + 1)]})

    with pytest.raises(ExportTooLargeError) as raised:
        export.to_workbook_bytes([("Kept", fits), ("Rejected", does_not)])

    assert raised.value.details["output_label"] == "Rejected"


def test_a_non_text_column_is_not_measured_for_cell_length() -> None:
    """Only string columns can exceed the character limit, so only they are read.

    Stated as a test because the guard's cost is otherwise invisible: a result
    of pure numbers is not scanned at all.
    """
    numbers = pl.DataFrame({"n": [1, 2, 3], "f": [1.5, 2.5, 3.5]})

    export.check_fits_worksheet(numbers, label="Numbers")  # must not raise

    assert export.to_xlsx_bytes(numbers, worksheet="R")


def test_a_null_only_text_column_does_not_confuse_the_guard() -> None:
    """A column with no values has no longest value, and that is not an error."""
    frame = pl.DataFrame({"note": [None, None]}, schema={"note": pl.String})

    export.check_fits_worksheet(frame, label="Empty")  # must not raise

    assert export.to_xlsx_bytes(frame, worksheet="R")