"""Generic tabular parsing for every Action (build plan 3.4-3.6).

One entry point, :func:`parse_tabular_file`, turns a stored upload into a
Polars dataframe plus the metadata the manifest records: which engine read the
file, which worksheet it came from, and the resulting shape.

Accuracy rules this module follows:

* **Nothing is guessed silently.** A parse failure is reported as a parse
  failure. The module never retries with progressively stranger delimiters or
  settings in the hope that one sticks (build plan 3.5).
* **Nothing is reinterpreted.** Values are read as the parser reads them; no
  date coercion, trimming or normalisation is applied on top
  (build plan section 3.3).
* **No engine switch is hidden.** If the preferred Excel engine fails and the
  compatibility fallback succeeds, the fallback is what gets recorded
  (build plan section 6.2).
"""

from __future__ import annotations

from collections.abc import Iterable, Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import fastexcel
import polars as pl

from app.errors import (
    AmbiguousWorkbookError,
    FileParseError,
    UnsupportedExtensionError,
)

CSV_EXTENSION = ".csv"
XLSX_EXTENSION = ".xlsx"

#: Extensions the POC accepts. Everything else is rejected explicitly rather
#: than attempted hopefully (build plan section 16).
SUPPORTED_EXTENSIONS: tuple[str, ...] = (CSV_EXTENSION, XLSX_EXTENSION)

#: Engine identifiers recorded in the manifest.
ENGINE_POLARS_CSV = "polars-csv"
ENGINE_FASTEXCEL = "fastexcel-calamine"
ENGINE_OPENPYXL = "openpyxl"


class _WorkbookStructureError(FileParseError):
    """A refusal about what the workbook contains, not an engine limitation.

    The compatibility fallback would reach the same conclusion, so these
    propagate immediately instead of triggering a retry.
    """


@dataclass(frozen=True)
class ParsedFile:
    """A parsed upload and how it was read."""

    frame: pl.DataFrame

    #: Which engine actually read the file, including a fallback if one was used.
    parser_engine: str

    #: Worksheet the rows came from; ``None`` for CSV.
    worksheet: str | None = None

    @property
    def row_count(self) -> int:
        return self.frame.height

    @property
    def column_count(self) -> int:
        return self.frame.width

    @property
    def columns(self) -> tuple[str, ...]:
        return tuple(self.frame.columns)


def parse_tabular_file(path: Path, extension: str) -> ParsedFile:
    """Read `path` as tabular data, dispatching on `extension`.

    Args:
        path: Location of the stored upload. Generated by the storage service,
            never supplied by a client.
        extension: Lowercase extension including the leading dot.

    Raises:
        UnsupportedExtensionError: the extension is not supported.
        FileParseError: the file could not be read as tabular data.
        AmbiguousWorkbookError: the workbook holds more than one data sheet.
    """
    normalised = extension.lower()
    if normalised == CSV_EXTENSION:
        return _parse_csv(path)
    if normalised == XLSX_EXTENSION:
        return _parse_xlsx(path)
    raise UnsupportedExtensionError(
        f"{normalised or 'That file type'} is not a supported file type. "
        f"Supported types are {_human_list(SUPPORTED_EXTENSIONS)}.",
        details={
            "extension": normalised,
            "supported_extensions": list(SUPPORTED_EXTENSIONS),
        },
    )


# ---------------------------------------------------------------------------
# CSV (build plan 3.5)
# ---------------------------------------------------------------------------


def _parse_csv(path: Path) -> ParsedFile:
    """Read an ordinary CSV file with Polars.

    Polars' own delimiter and type inference is used as-is. Date parsing is
    deliberately left off: a column of date-shaped text stays text unless an
    Action asks for something else, so no value is silently retyped.
    """
    try:
        frame = pl.read_csv(path)
    except pl.exceptions.NoDataError as exc:
        raise FileParseError(
            "The uploaded CSV file is empty.", details={"reason": str(exc)}
        ) from exc
    except Exception as exc:
        raise FileParseError(
            "The uploaded CSV file could not be read. It may be malformed or "
            "may not be a CSV file.",
            details={"reason": str(exc)},
        ) from exc
    return ParsedFile(frame=frame, parser_engine=ENGINE_POLARS_CSV)


# ---------------------------------------------------------------------------
# XLSX (build plan 3.6 and section 17)
# ---------------------------------------------------------------------------


def _parse_xlsx(path: Path) -> ParsedFile:
    """Read a single-data-sheet XLSX workbook.

    fastexcel (calamine) is the preferred engine. If it cannot open the
    workbook at all, openpyxl is tried as the compatibility fallback and
    whichever engine succeeded is what the manifest records.

    A refusal about the workbook's *structure* — no data sheet, or several —
    is never retried: the fallback would reach the same conclusion.

    Both engines read the values stored in the workbook. Neither evaluates
    formulas and neither executes macros (build plan section 17 and 7F).
    """
    try:
        return _parse_xlsx_with_fastexcel(path)
    except (AmbiguousWorkbookError, _WorkbookStructureError):
        raise
    except Exception as primary_error:
        try:
            return _parse_xlsx_with_openpyxl(path)
        except (AmbiguousWorkbookError, _WorkbookStructureError):
            raise
        except Exception as fallback_error:
            raise FileParseError(
                "The uploaded Excel workbook could not be read. It may be "
                "corrupt, password-protected, or not a genuine .xlsx file.",
                details={
                    "primary_engine": ENGINE_FASTEXCEL,
                    "primary_reason": str(primary_error),
                    "fallback_engine": ENGINE_OPENPYXL,
                    "fallback_reason": str(fallback_error),
                },
            ) from fallback_error


def _parse_xlsx_with_fastexcel(path: Path) -> ParsedFile:
    """Read the workbook with the preferred engine."""
    reader = fastexcel.read_excel(str(path))
    worksheet = _select_data_worksheet(
        {name: _fastexcel_sheet_has_data(reader, name) for name in reader.sheet_names}
    )
    sheet = reader.load_sheet(worksheet, header_row=0)
    return ParsedFile(
        frame=sheet.to_polars(),
        parser_engine=ENGINE_FASTEXCEL,
        worksheet=worksheet,
    )


def _fastexcel_sheet_has_data(reader: fastexcel.ExcelReader, name: str) -> bool:
    """Whether a worksheet contains any cells at all.

    ``header_row=None`` counts every row, so a sheet holding only a header row
    still counts as a data sheet — a header-only upload is a legitimate dataset
    with zero rows, not an empty sheet.
    """
    try:
        sheet = reader.load_sheet(name, header_row=None)
    except Exception:
        # A sheet that will not load cannot be the one unambiguous data sheet.
        return False
    return sheet.total_height > 0 and sheet.width > 0


def _parse_xlsx_with_openpyxl(path: Path) -> ParsedFile:
    """Read the workbook with the compatibility fallback engine.

    ``data_only=True`` returns the values Excel last stored for formula cells
    rather than the formula text. openpyxl neither evaluates formulas nor runs
    macros.
    """
    import openpyxl

    workbook = openpyxl.load_workbook(
        path, read_only=True, data_only=True, keep_links=False
    )
    try:
        worksheet_name = _select_data_worksheet(
            {
                name: _openpyxl_sheet_has_data(workbook[name])
                for name in workbook.sheetnames
            }
        )
        frame = _frame_from_rows(
            workbook[worksheet_name].iter_rows(values_only=True)
        )
    finally:
        workbook.close()

    return ParsedFile(
        frame=frame, parser_engine=ENGINE_OPENPYXL, worksheet=worksheet_name
    )


def _openpyxl_sheet_has_data(worksheet: Any) -> bool:
    """Whether an openpyxl worksheet holds any cells.

    In read-only mode the recorded dimensions come from the workbook's own
    dimension tag, which some writers omit. When they are unavailable the sheet
    is probed by reading its first row rather than assumed empty.
    """
    max_row = getattr(worksheet, "max_row", None)
    max_column = getattr(worksheet, "max_column", None)
    if max_row is not None and max_column is not None:
        return max_row > 0 and max_column > 0
    return any(True for _ in worksheet.iter_rows(max_row=1, values_only=True))


def _frame_from_rows(rows: Iterable[tuple[Any, ...]]) -> pl.DataFrame:
    """Build a dataframe from openpyxl's row tuples, first row as the header."""
    iterator: Iterator[tuple[Any, ...]] = iter(rows)
    try:
        header = next(iterator)
    except StopIteration:
        raise _WorkbookStructureError(
            "The selected worksheet is empty.", details={"worksheet_empty": True}
        ) from None

    column_names = [
        str(value) if value is not None else f"column_{index + 1}"
        for index, value in enumerate(header)
    ]

    data_rows: list[list[Any]] = []
    for row in iterator:
        values = list(row[: len(column_names)])
        # Pad short rows so every record matches the header width.
        values.extend([None] * (len(column_names) - len(values)))
        data_rows.append(values)

    return pl.DataFrame(
        data_rows or None,
        schema=column_names,
        orient="row",
        infer_schema_length=None,
    )


def _select_data_worksheet(sheets: dict[str, bool]) -> str:
    """Return the one worksheet holding data, or refuse to choose.

    Build plan section 17: the POC must not silently pick a worksheet from a
    workbook containing several plausible data sheets. Exactly one data sheet
    is unambiguous; anything else is reported to the user.

    Raises:
        _WorkbookStructureError: no worksheet contains data.
        AmbiguousWorkbookError: more than one worksheet contains data.
    """
    populated = [name for name, has_data in sheets.items() if has_data]

    if len(populated) == 1:
        return populated[0]

    if not populated:
        raise _WorkbookStructureError(
            "The uploaded Excel workbook contains no data.",
            details={"worksheets": list(sheets)},
        )

    raise AmbiguousWorkbookError(
        "This workbook contains multiple worksheets. The POC currently "
        "requires a workbook containing one data worksheet. Save the required "
        "worksheet as its own workbook or CSV and try again.",
        details={"worksheets_with_data": populated, "worksheets": list(sheets)},
    )


def _human_list(values: tuple[str, ...]) -> str:
    """Join `values` for a user-facing message: 'a, b and c'."""
    if len(values) <= 1:
        return "".join(values)
    return f"{', '.join(values[:-1])} and {values[-1]}"