"""The synthetic spreadsheet fixture system (build plan 6H.1, 6H.2, 6H.8).

Every dataset ForgeXL's automated tests process is **built here, in memory,
from Python literals**. The repository contains no `.csv` or `.xlsx` blob, no
company spreadsheet and no file that had to be saved by hand from Excel — a
rule build plan 6H.8 states and `test_spreadsheet_fixtures.py` asserts.

Two shapes are enough for everything the build plan's fixture list needs:

    Table      one dataset: a header plus rows. Renders as CSV *or* as a
               one-worksheet workbook, so the same fixture proves that both
               upload paths reach the same result.
    Workbook   named worksheets in order. The cases that are *about* workbook
               structure — several data sheets, a workbook holding nothing —
               cannot be expressed as a single table.

Determinism is the property that makes any of this evidence (build plan 6H.1).
Nothing here reads a clock, a random source, an environment variable or the
filesystem, so a fixture's bytes are a pure function of its literals and
`as_csv()` returns the identical bytes on every call, on every machine, in
every process. :func:`large_table` is generated by arithmetic on the row index
for the same reason.

Two writer settings matter and are not defaults:

* ``strings_to_formulas=False`` — xlsxwriter otherwise turns any cell whose
  text begins with ``=`` into a *formula*. A fixture builder that silently
  converts text into something else cannot be used to prove the application
  never does (build plan section 16). This is the same setting
  `app.services.export` applies for the same reason.
* ``in_memory=True`` — xlsxwriter otherwise spools workbook parts through the
  OS temporary directory. A fixture system for a runtime that writes nothing
  should not itself write files (build plan 6F.2).
"""

from __future__ import annotations

import csv
import io
from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any

import xlsxwriter

#: The worksheet a single-table fixture is written to when nothing else is
#: asked for. Named for what it holds rather than for Excel's "Sheet1".
DEFAULT_WORKSHEET = "Data"

CSV_EXTENSION = ".csv"
XLSX_EXTENSION = ".xlsx"

#: The two upload formats every `Table` can be rendered as. Tests parametrise
#: over this so a fixture is never proved in one format only.
UPLOAD_EXTENSIONS: tuple[str, ...] = (CSV_EXTENSION, XLSX_EXTENSION)

#: Options every fixture workbook is written with. See the module docstring:
#: neither is xlsxwriter's default and both are deliberate.
_WORKBOOK_OPTIONS: dict[str, object] = {
    "in_memory": True,
    "strings_to_formulas": False,
}

#: Rows of a worksheet, header included; ``None`` is a blank cell.
Rows = tuple[tuple[Any, ...], ...]


def _write_workbook(sheets: Sequence[tuple[str, Rows]]) -> bytes:
    """Render named worksheets to workbook bytes.

    A `None` cell is skipped rather than written, which is what leaves a
    genuinely blank cell in the file — writing an empty string would store a
    string, and the two are different things to both Excel and the parser.
    """
    buffer = io.BytesIO()
    workbook = xlsxwriter.Workbook(buffer, _WORKBOOK_OPTIONS)
    for name, rows in sheets:
        worksheet = workbook.add_worksheet(name)
        for row_index, row in enumerate(rows):
            for column_index, value in enumerate(row):
                if value is not None:
                    worksheet.write(row_index, column_index, value)
    workbook.close()
    return buffer.getvalue()


@dataclass(frozen=True)
class Table:
    """One synthetic dataset, renderable as either upload format.

    `name` identifies the fixture in test IDs; `description` says what the
    dataset is *for*, so a failure names the scenario rather than a row index.
    """

    name: str
    description: str
    header: tuple[str, ...]
    rows: Rows

    @property
    def row_count(self) -> int:
        return len(self.rows)

    @property
    def column_count(self) -> int:
        return len(self.header)

    def as_csv(self) -> bytes:
        """Render as CSV bytes.

        `None` becomes an empty field, which is how a CSV expresses a blank
        cell. Line endings are fixed at ``\\n`` so the bytes do not depend on
        the platform the suite runs on.
        """
        buffer = io.StringIO()
        writer = csv.writer(buffer, lineterminator="\n")
        writer.writerow(self.header)
        writer.writerows(
            ["" if value is None else value for value in row] for row in self.rows
        )
        return buffer.getvalue().encode("utf-8")

    def as_xlsx(self, *, worksheet: str = DEFAULT_WORKSHEET) -> bytes:
        """Render as a workbook holding this table on one worksheet."""
        return _write_workbook([(worksheet, (self.header, *self.rows))])

    def payload(self, extension: str) -> bytes:
        """Render in whichever upload format `extension` names."""
        if extension == CSV_EXTENSION:
            return self.as_csv()
        if extension == XLSX_EXTENSION:
            return self.as_xlsx()
        raise ValueError(f"No fixture renderer for {extension!r}.")

    def filename(self, extension: str) -> str:
        """A plausible upload filename for this fixture."""
        return f"{self.name}{extension}"

    def with_columns(self, *columns: str) -> "Table":
        """This table narrowed to `columns`, in the order given.

        Used to state an expected output by *construction* — "the Product
        Master is these six columns of the upload, deduplicated" — rather than
        by copying values into a second literal that could drift from the
        first.
        """
        indexes = [self.header.index(name) for name in columns]
        return Table(
            name=f"{self.name}-{'-'.join(columns).lower()}",
            description=f"{self.description} (narrowed to {', '.join(columns)})",
            header=tuple(columns),
            rows=tuple(tuple(row[index] for index in indexes) for row in self.rows),
        )

    def deduplicated(self) -> "Table":
        """This table with exactly-repeated rows dropped, first kept.

        The expected output of the Exact Duplicate Remover, computed here from
        the fixture's own literals with plain Python — deliberately *not* by
        calling Polars or the Action, so a test comparing the two is comparing
        two independent implementations rather than one against itself.
        """
        seen: set[tuple[Any, ...]] = set()
        kept: list[tuple[Any, ...]] = []
        for row in self.rows:
            if row not in seen:
                seen.add(row)
                kept.append(row)
        return Table(
            name=f"{self.name}-deduplicated",
            description=f"{self.description} (exact duplicates removed)",
            header=self.header,
            rows=tuple(kept),
        )


@dataclass(frozen=True)
class Workbook:
    """A synthetic workbook with named worksheets, in order.

    For the fixture scenarios that are about a workbook's *structure* rather
    than about a dataset: several plausible data sheets, or none at all.
    """

    name: str
    description: str
    sheets: tuple[tuple[str, Rows], ...]

    @property
    def sheet_names(self) -> tuple[str, ...]:
        return tuple(name for name, _ in self.sheets)

    def as_xlsx(self) -> bytes:
        return _write_workbook(self.sheets)

    def filename(self) -> str:
        return f"{self.name}{XLSX_EXTENSION}"


# ---------------------------------------------------------------------------
# The fixture catalogue (build plan 6H.2)
#
# One entry per scenario the build plan lists, restricted to scenarios that
# are meaningful for what ForgeXL actually supports today: tabular CSV and
# single-data-sheet XLSX, read exactly as stored.
# ---------------------------------------------------------------------------

SIMPLE_TABLE = Table(
    name="simple-table",
    description="An ordinary dataset with nothing unusual in it.",
    header=("Region", "Product", "Units"),
    rows=(
        ("North", "Widget", 10),
        ("South", "Gadget", 25),
        ("East", "Doohickey", 7),
    ),
)

BLANK_ROWS = Table(
    name="blank-rows",
    description=(
        "A dataset interrupted by rows that are blank in every column. They "
        "are rows of data like any other and must survive as rows of nulls: "
        "dropping them would be silently discarding user data."
    ),
    header=("Region", "Product", "Units"),
    rows=(
        ("North", "Widget", 10),
        (None, None, None),
        ("South", "Gadget", 25),
        (None, None, None),
        ("East", "Doohickey", 7),
    ),
)

BLANK_CELLS = Table(
    name="blank-cells",
    description=(
        "Blanks scattered through otherwise complete rows, including a blank "
        "in the first data row so the column's type is inferred with one "
        "present."
    ),
    header=("Region", "Product", "Note"),
    rows=(
        ("North", "Widget", None),
        (None, "Gadget", "restocked"),
        ("East", None, "backorder"),
        ("West", "Doohickey", None),
    ),
)

DUPLICATE_ROWS = Table(
    name="duplicate-rows",
    description=(
        "Rows repeated exactly, plus near-misses that differ in one column "
        "only. The near-misses are the trap: they must not be removed."
    ),
    header=("Region", "Product", "Units"),
    rows=(
        ("North", "Widget", 10),
        ("North", "Widget", 10),
        ("South", "Widget", 10),
        ("North", "Widget", 11),
        ("North", "Widget", 10),
        ("South", "Widget", 10),
    ),
)

DUPLICATE_KEYS = Table(
    name="duplicate-keys",
    description=(
        "One key repeated across rows that differ elsewhere. Nothing may "
        "collapse them: a repeated key is not a repeated row."
    ),
    header=("SKU", "Warehouse", "Units"),
    rows=(
        ("SKU-1", "North", 10),
        ("SKU-1", "South", 4),
        ("SKU-1", "East", 12),
        ("SKU-2", "North", 3),
    ),
)

MIXED_VALUES = Table(
    name="mixed-values",
    description=(
        "A column holding numbers and text together — the case a spreadsheet "
        "produces whenever someone types 'n/a' into a numeric column."
    ),
    header=("Code", "Value"),
    rows=(
        ("A", 10),
        ("B", "n/a"),
        ("C", 2.5),
        ("D", None),
        ("E", -3),
        ("F", 0),
    ),
)

DATES = Table(
    name="dates",
    description=(
        "Dates written as text, in the ISO form. ForgeXL reads them as the "
        "text they are: nothing retypes a date-shaped string."
    ),
    header=("Order Id", "Received"),
    rows=(
        ("ORD-1", "2026-01-31"),
        ("ORD-2", "2026-02-28"),
        ("ORD-3", "2026-12-01"),
    ),
)

MALFORMED_DATES = Table(
    name="malformed-dates",
    description=(
        "Date-shaped text that is not a date: a 30th of February, a 13th "
        "month, a two-digit year, a sentence. None may be repaired, reordered "
        "or turned into a null — the value reaches the result as written."
    ),
    header=("Order Id", "Received"),
    rows=(
        ("ORD-1", "2026-02-30"),
        ("ORD-2", "2026-13-01"),
        ("ORD-3", "31/02/26"),
        ("ORD-4", "not a date"),
        ("ORD-5", "2026-01-31"),
    ),
)

UNICODE_TEXT = Table(
    name="unicode-text",
    description=(
        "Non-Latin scripts, an apostrophe and a comma inside a value. The "
        "comma is the CSV trap and the apostrophe is the Excel one."
    ),
    header=("Producer", "City"),
    rows=(
        ("東京商事", "東京"),
        ("Ζορμπάς", "Αθήνα"),
        ("Пётр Смирнов", "Москва"),
        ("O'Brien & Sons, Ltd.", "Dublin"),
        ("‘smart quotes’", "—em dash—"),
    ),
)

ACCENTED_TEXT = Table(
    name="accented-text",
    description=(
        "Names that differ only by their accents. Stripping or folding them "
        "would collapse two real products into one and lose a row of company "
        "data, so both must survive as written."
    ),
    header=("Producer", "Selection"),
    rows=(
        ("Château Margaux", "Réserve"),
        ("Chateau Margaux", "Reserve"),
        ("Domaine Père et Fils", "Côtes du Rhône"),
        ("Domaine Pere et Fils", "Cotes du Rhone"),
        ("Bodegas Muñoz", "Añejo"),
    ),
)

UNUSUAL_COLUMN_NAMES = Table(
    name="unusual-column-names",
    description=(
        "Column names carrying spaces, punctuation, a leading space, an "
        "accent, a leading '=' and a trailing period. Names are identifiers "
        "here, not text to be tidied: each must arrive exactly as uploaded."
    ),
    header=(
        "  Leading Space",
        "Total (%)",
        "Ünïcode Héader",
        "=Not A Formula",
        "Column.With.Dots",
        "UPPER lower",
    ),
    rows=(
        ("a", 1, "x", "p", 0.5, "m"),
        ("b", 2, "y", "q", 1.5, "n"),
    ),
)

EXTRA_COLUMNS = Table(
    name="extra-columns",
    description=(
        "A sales extract holding the Product Master Builder's six required "
        "columns plus two it does not use, in an order that does not match "
        "the output's. The extras must be dropped and the order fixed."
    ),
    header=(
        "Order Id",
        "SKU",
        "Producer",
        "Supplier",
        "Selection",
        "Vintage",
        "Volume",
        "Quantity",
    ),
    rows=(
        ("ORD-1", "SKU-1", "Château Margaux", "Acme", "Réserve", 2019, "750ml", 6),
        ("ORD-2", "SKU-1", "Château Margaux", "Acme", "Réserve", 2019, "750ml", 12),
        ("ORD-3", "SKU-2", "Bodegas Muñoz", "Acme", "Añejo", 2020, "1.5L", 1),
        ("ORD-4", "SKU-1", "Château Margaux", "Acme", "Réserve", 2020, "750ml", 3),
        ("ORD-5", "SKU-3", "Domaine Père et Fils", "Vinco", None, None, "750ml", 2),
        ("ORD-6", "SKU-3", "Domaine Pere et Fils", "Vinco", None, None, "750ml", 5),
    ),
)

MISSING_REQUIRED_COLUMNS = Table(
    name="missing-required-columns",
    description=(
        "A sales extract that is missing four of the Product Master "
        "Builder's six required columns, and misspells a fifth as 'Sku'. "
        "Column names are compared exactly, so this is refused rather than "
        "guessed at."
    ),
    header=("Order Id", "Sku", "Supplier", "Quantity"),
    rows=(
        ("ORD-1", "SKU-1", "Acme", 6),
        ("ORD-2", "SKU-2", "Vinco", 3),
    ),
)

HEADER_ONLY = Table(
    name="header-only",
    description=(
        "Column names and no rows. A legitimate dataset with zero rows, not "
        "an empty file — the two report different errors."
    ),
    header=("Region", "Product", "Units"),
    rows=(),
)

SINGLE_ROW = Table(
    name="single-row",
    description="The smallest dataset that still holds data.",
    header=("Region", "Product", "Units"),
    rows=(("North", "Widget", 10),),
)

#: Every single-table fixture, for tests that sweep the whole catalogue.
CATALOGUE: tuple[Table, ...] = (
    SIMPLE_TABLE,
    BLANK_ROWS,
    BLANK_CELLS,
    DUPLICATE_ROWS,
    DUPLICATE_KEYS,
    MIXED_VALUES,
    DATES,
    MALFORMED_DATES,
    UNICODE_TEXT,
    ACCENTED_TEXT,
    UNUSUAL_COLUMN_NAMES,
    EXTRA_COLUMNS,
    MISSING_REQUIRED_COLUMNS,
    HEADER_ONLY,
    SINGLE_ROW,
)


# ---------------------------------------------------------------------------
# Workbook-structure fixtures (build plan 6H.2: multiple worksheets, empty
# workbook)
# ---------------------------------------------------------------------------

MULTIPLE_WORKSHEETS = Workbook(
    name="multiple-worksheets",
    description=(
        "Two worksheets that both hold data. ForgeXL refuses to choose "
        "between them rather than picking one silently (build plan §17)."
    ),
    sheets=(
        ("January", (("Region", "Units"), ("North", 10))),
        ("February", (("Region", "Units"), ("South", 25))),
    ),
)

ONE_DATA_SHEET_AMONG_BLANKS = Workbook(
    name="one-data-sheet-among-blanks",
    description=(
        "One data worksheet beside empty ones. Unambiguous: an empty sheet "
        "is not a plausible data sheet."
    ),
    sheets=(
        ("Notes", ()),
        ("Data", (("Region", "Product", "Units"), ("North", "Widget", 10))),
        ("Scratch", ()),
    ),
)

EMPTY_WORKBOOK = Workbook(
    name="empty-workbook",
    description="A workbook whose only worksheet holds nothing at all.",
    sheets=(("Sheet1", ()),),
)

WORKBOOKS: tuple[Workbook, ...] = (
    MULTIPLE_WORKSHEETS,
    ONE_DATA_SHEET_AMONG_BLANKS,
    EMPTY_WORKBOOK,
)


# ---------------------------------------------------------------------------
# The larger dataset (build plan 6H.2)
# ---------------------------------------------------------------------------

#: Distinct product combinations :func:`large_table` cycles through.
#:
#: Every column of the generated row is a function of ``index % PRODUCT_POOL``,
#: so two rows are identical exactly when their indexes are congruent modulo
#: this number. That makes both proof Actions' expected output computable
#: without deduplicating anything: a table of `n` rows holds
#: ``min(n, PRODUCT_POOL)`` distinct rows, and they appear in generation order.
PRODUCT_POOL = 250

#: Values cycled through the generated columns. Coprime lengths against
#: `PRODUCT_POOL` are not needed — the SKU alone makes each pool entry
#: distinct — but varying them keeps the data from looking like one repeated
#: row with a changing ID.
_SUPPLIERS = ("Acme Imports", "Vinco", "Global Cellars")
_PRODUCERS = ("Château Margaux", "Bodegas Muñoz", "Domaine Père et Fils", "Weingut Löwen")
_SELECTIONS = ("Réserve", "Estate", "Añejo", "Grand Cru", None)
_VOLUMES = ("750ml", "1.5L", "375ml")

#: Column names of a generated large table — the Product Master Builder's six
#: required columns plus one it must drop, so one fixture drives both Actions.
LARGE_TABLE_HEADER: tuple[str, ...] = (
    "SKU",
    "Vintage",
    "Supplier",
    "Producer",
    "Selection",
    "Volume",
    "Units",
)


def large_table(row_count: int, *, name: str | None = None) -> Table:
    """Generate a deterministic dataset of `row_count` rows.

    Build plan 6H.2 asks for a larger fixture, and 6H.1 for fixtures that are
    generated rather than stored. Generating this one keeps a multi-megabyte
    blob out of the repository entirely, at the cost of building it per run —
    the trade the project takes, because a stored fixture is a second artifact
    that can drift from the code that reads it.

    Every value derives from ``index % PRODUCT_POOL`` by arithmetic alone, so
    the result depends on nothing but `row_count`: no clock, no random source,
    no platform detail. Two rows are identical exactly when their indexes are
    congruent modulo :data:`PRODUCT_POOL`, which is what makes both Actions'
    expected output a closed-form number rather than something a test has to
    deduplicate for itself.

    Args:
        row_count: Rows to generate. Zero produces a header-only table.
        name: Fixture name; defaults to one naming the size.
    """
    if row_count < 0:
        raise ValueError("row_count may not be negative.")

    rows = tuple(_large_row(index) for index in range(row_count))
    return Table(
        name=name or f"large-{row_count}",
        description=(
            f"{row_count:,} generated rows cycling through {PRODUCT_POOL} "
            "distinct products."
        ),
        header=LARGE_TABLE_HEADER,
        rows=rows,
    )


def _large_row(index: int) -> tuple[Any, ...]:
    """One generated row, a pure function of `index`."""
    product = index % PRODUCT_POOL
    return (
        f"SKU-{product:05d}",
        2000 + (product % 25),
        _SUPPLIERS[product % len(_SUPPLIERS)],
        _PRODUCERS[product % len(_PRODUCERS)],
        _SELECTIONS[product % len(_SELECTIONS)],
        _VOLUMES[product % len(_VOLUMES)],
        product % 97,
    )


def distinct_rows_in_large_table(row_count: int) -> int:
    """Rows a `large_table(row_count)` holds once duplicates are removed."""
    return min(row_count, PRODUCT_POOL)